module Knockapi
  module Models
    module Messages
      type batch_unarchive_response = ::Array[Knockapi::Message]

      BatchUnarchiveResponse: Knockapi::Internal::Type::Converter
    end
  end
end
