module Knockapi
  module Models
    module Messages
      type batch_mark_as_read_response = ::Array[Knockapi::Models::Message]

      BatchMarkAsReadResponse: batch_mark_as_read_response
    end
  end
end
