module Knockapi
  module Models
    module Messages
      type batch_mark_as_unseen_response = ::Array[Knockapi::Models::Message]

      BatchMarkAsUnseenResponse: Knockapi::Internal::Type::Converter
    end
  end
end
