module Knockapi
  module Models
    module Messages
      type batch_mark_as_interacted_params =
        { message_ids: ::Array[String], metadata: ::Hash[Symbol, top]? }
        & Knockapi::request_parameters

      class BatchMarkAsInteractedParams < Knockapi::BaseModel
        extend Knockapi::Type::RequestParameters::Converter
        include Knockapi::RequestParameters

        attr_accessor message_ids: ::Array[String]

        attr_accessor metadata: ::Hash[Symbol, top]?

        def initialize: (
          message_ids: ::Array[String],
          ?metadata: ::Hash[Symbol, top]?,
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> Knockapi::Models::Messages::batch_mark_as_interacted_params
      end
    end
  end
end
