module Knockapi
  module Models
    module Messages
      type batch_archive_response = ::Array[Knockapi::Models::Message]

      BatchArchiveResponse: Knockapi::Internal::Type::Converter
    end
  end
end
