module Knockapi
  module Models
    module Messages
      type batch_mark_as_unread_params =
        { message_ids: ::Array[String] }
        & Knockapi::Internal::Type::request_parameters

      class BatchMarkAsUnreadParams < Knockapi::Internal::Type::BaseModel
        extend Knockapi::Internal::Type::RequestParameters::Converter
        include Knockapi::Internal::Type::RequestParameters

        attr_accessor message_ids: ::Array[String]

        def initialize: (
          message_ids: ::Array[String],
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> {
          message_ids: ::Array[String],
          request_options: Knockapi::RequestOptions
        }
      end
    end
  end
end
