module Knockapi
  module Models
    module Messages
      type batch_mark_as_seen_response = ::Array[Knockapi::Models::Message]

      BatchMarkAsSeenResponse: batch_mark_as_seen_response
    end
  end
end
