module Knockapi
  module Models
    module Messages
      type batch_mark_as_unread_response = ::Array[Knockapi::Message]

      BatchMarkAsUnreadResponse: Knockapi::Internal::Type::Converter
    end
  end
end
