module Knockapi
  module Models
    module Messages
      type batch_get_content_response = ::Array[Knockapi::MessageContents]

      BatchGetContentResponse: Knockapi::Internal::Type::Converter
    end
  end
end
