module Knockapi
  module Models
    module Messages
      type batch_get_content_params =
        { message_ids: ::Array[String] } & Knockapi::request_parameters

      class BatchGetContentParams < Knockapi::BaseModel
        extend Knockapi::RequestParameters::Converter
        include Knockapi::RequestParameters

        attr_accessor message_ids: ::Array[String]

        def initialize:
          (
            message_ids: ::Array[String],
            request_options: Knockapi::request_opts
          ) -> void
          | (
            ?Knockapi::Models::Messages::batch_get_content_params
            | Knockapi::BaseModel data
          ) -> void

        def to_hash: -> Knockapi::Models::Messages::batch_get_content_params
      end
    end
  end
end
