module Knock
  module Resources
    class Providers
      class Slack
        def check_auth:
          (
            String channel_id,
            Knock::Models::Providers::SlackCheckAuthParams
            | ::Hash[Symbol, top] params
          ) -> Knock::Models::Providers::SlackCheckAuthResponse
          | (
            String channel_id,
            access_token_object: String,
            request_options: Knock::request_opts
          ) -> Knock::Models::Providers::SlackCheckAuthResponse

        def list_channels:
          (
            String channel_id,
            Knock::Models::Providers::SlackListChannelsParams
            | ::Hash[Symbol, top] params
          ) -> Knock::Models::Providers::SlackListChannelsResponse
          | (
            String channel_id,
            access_token_object: String,
            query_options: Knock::Models::Providers::SlackListChannelsParams::QueryOptions,
            request_options: Knock::request_opts
          ) -> Knock::Models::Providers::SlackListChannelsResponse

        def revoke_access:
          (
            String channel_id,
            Knock::Models::Providers::SlackRevokeAccessParams
            | ::Hash[Symbol, top] params
          ) -> String
          | (
            String channel_id,
            access_token_object: String,
            request_options: Knock::request_opts
          ) -> String

        def initialize: (client: Knock::Client) -> void
      end
    end
  end
end
