module Knockapi
  module Models
    module Users
      type feed_get_settings_response =
        { features: Knockapi::Models::Users::FeedGetSettingsResponse::Features }

      class FeedGetSettingsResponse < Knockapi::BaseModel
        attr_accessor features: Knockapi::Models::Users::FeedGetSettingsResponse::Features

        def initialize:
          (
            features: Knockapi::Models::Users::FeedGetSettingsResponse::Features
          ) -> void
          | (
            ?Knockapi::Models::Users::feed_get_settings_response
            | Knockapi::BaseModel data
          ) -> void

        def to_hash: -> Knockapi::Models::Users::feed_get_settings_response

        type features = { branding_required: bool }

        class Features < Knockapi::BaseModel
          attr_accessor branding_required: bool

          def initialize:
            (branding_required: bool) -> void
            | (
              ?Knockapi::Models::Users::FeedGetSettingsResponse::features
              | Knockapi::BaseModel data
            ) -> void

          def to_hash: -> Knockapi::Models::Users::FeedGetSettingsResponse::features
        end
      end
    end
  end
end
