module Knockapi
  module Models
    module Users
      type feed_get_settings_params = {  } & Knockapi::request_parameters

      class FeedGetSettingsParams < Knockapi::BaseModel
        extend Knockapi::Type::RequestParameters::Converter
        include Knockapi::RequestParameters

        def initialize: (?request_options: Knockapi::request_opts) -> void

        def to_hash: -> Knockapi::Models::Users::feed_get_settings_params
      end
    end
  end
end
