module Knockapi
  module Models
    module Users
      type feed_get_settings_response =
        { features: Knockapi::Models::Users::FeedGetSettingsResponse::Features }

      class FeedGetSettingsResponse < Knockapi::Internal::Type::BaseModel
        attr_accessor features: Knockapi::Models::Users::FeedGetSettingsResponse::Features

        def initialize: (
          features: Knockapi::Models::Users::FeedGetSettingsResponse::Features
        ) -> void

        def to_hash: -> {
          features: Knockapi::Models::Users::FeedGetSettingsResponse::Features
        }

        type features = { branding_required: bool }

        class Features < Knockapi::Internal::Type::BaseModel
          attr_accessor branding_required: bool

          def initialize: (branding_required: bool) -> void

          def to_hash: -> { branding_required: bool }
        end
      end
    end
  end
end
