module Knockapi
  module Models
    module Users
      type guide_archived_request =
        {
          channel_id: String,
          guide_id: String,
          guide_key: String,
          guide_step_ref: String,
          is_final: bool,
          tenant: String,
          unthrottled: bool
        }

      class GuideArchivedRequest < Knockapi::Internal::Type::BaseModel
        attr_accessor channel_id: String

        attr_accessor guide_id: String

        attr_accessor guide_key: String

        attr_accessor guide_step_ref: String

        attr_reader is_final: bool?

        def is_final=: (bool) -> bool

        attr_reader tenant: String?

        def tenant=: (String) -> String

        attr_reader unthrottled: bool?

        def unthrottled=: (bool) -> bool

        def initialize: (
          channel_id: String,
          guide_id: String,
          guide_key: String,
          guide_step_ref: String,
          ?is_final: bool,
          ?tenant: String,
          ?unthrottled: bool
        ) -> void

        def to_hash: -> {
          channel_id: String,
          guide_id: String,
          guide_key: String,
          guide_step_ref: String,
          is_final: bool,
          tenant: String,
          unthrottled: bool
        }
      end
    end
  end
end
