module Knockapi
  module Models
    module Users
      type guide_mark_message_as_interacted_response = { status: String }

      class GuideMarkMessageAsInteractedResponse < Knockapi::Internal::Type::BaseModel
        attr_accessor status: String

        def initialize: (status: String) -> void
      end
    end
  end
end
