module Knock
  module Resources
    class Tenants
      attr_reader bulk: Knock::Resources::Tenants::Bulk

      def list:
        (
          ?Knock::Models::TenantListParams | ::Hash[Symbol, top] params
        ) -> Knock::EntriesCursor[Knock::Models::Tenant]
        | (
          after: String,
          before: String,
          page_size: Integer,
          request_options: Knock::request_opts
        ) -> Knock::EntriesCursor[Knock::Models::Tenant]

      def delete:
        (
          String tenant_id,
          ?Knock::Models::TenantDeleteParams | ::Hash[Symbol, top] params
        ) -> String
        | (String tenant_id, request_options: Knock::request_opts) -> String

      def get:
        (
          String tenant_id,
          ?Knock::Models::TenantGetParams | ::Hash[Symbol, top] params
        ) -> Knock::Models::Tenant
        | (
          String tenant_id,
          request_options: Knock::request_opts
        ) -> Knock::Models::Tenant

      def set:
        (
          String tenant_id,
          ?Knock::Models::TenantSetParams | ::Hash[Symbol, top] params
        ) -> Knock::Models::Tenant
        | (
          String tenant_id,
          channel_data: Knock::Models::inline_channel_data_request?,
          preferences: Knock::Models::inline_preference_set_request?,
          settings: Knock::Models::TenantSetParams::Settings,
          request_options: Knock::request_opts
        ) -> Knock::Models::Tenant

      def initialize: (client: Knock::Client) -> void
    end
  end
end
