module Knock
  module Resources
    class Tenants
      class Bulk
        def delete:
          (
            Knock::Models::Tenants::BulkDeleteParams
            | ::Hash[Symbol, top] params
          ) -> Knock::Models::BulkOperation
          | (
            tenant_ids: ::Array[String],
            request_options: Knock::request_opts
          ) -> Knock::Models::BulkOperation

        def set:
          (
            Knock::Models::Tenants::BulkSetParams | ::Hash[Symbol, top] params
          ) -> Knock::Models::BulkOperation
          | (
            tenants: ::Array[Knock::Models::inline_tenant_request],
            request_options: Knock::request_opts
          ) -> Knock::Models::BulkOperation

        def initialize: (client: Knock::Client) -> void
      end
    end
  end
end
