---
max_files: 0
include:
  - '*.gemspec'
  - 'Rakefile'
  - 'examples/**/*.rb'
  - 'lib/**/*.rb'
  - 'test/knockapi/resource_namespaces.rb'
  - 'test/knockapi/test_helper.rb'
exclude:
  - 'rbi/**/*'
