module Knockapi
  module Models
    module Providers
      type ms_team_check_auth_params =
        { ms_teams_tenant_object: String } & Knockapi::request_parameters

      class MsTeamCheckAuthParams < Knockapi::BaseModel
        extend Knockapi::RequestParameters::Converter
        include Knockapi::RequestParameters

        attr_accessor ms_teams_tenant_object: String

        def initialize: (
          ms_teams_tenant_object: String,
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> Knockapi::Models::Providers::ms_team_check_auth_params
      end
    end
  end
end
