module Knockapi
  module Models
    module Providers
      type ms_team_list_teams_params =
        {
          ms_teams_tenant_object: String,
          query_options: Knockapi::Models::Providers::MsTeamListTeamsParams::QueryOptions
        }
        & Knockapi::request_parameters

      class MsTeamListTeamsParams < Knockapi::BaseModel
        extend Knockapi::RequestParameters::Converter
        include Knockapi::RequestParameters

        attr_accessor ms_teams_tenant_object: String

        attr_reader query_options: Knockapi::Models::Providers::MsTeamListTeamsParams::QueryOptions?

        def query_options=: (
          Knockapi::Models::Providers::MsTeamListTeamsParams::QueryOptions
        ) -> Knockapi::Models::Providers::MsTeamListTeamsParams::QueryOptions

        def initialize: (
          ms_teams_tenant_object: String,
          ?query_options: Knockapi::Models::Providers::MsTeamListTeamsParams::QueryOptions,
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> Knockapi::Models::Providers::ms_team_list_teams_params

        type query_options =
          { filter: String, select_: String, skiptoken: String, top: Integer }

        class QueryOptions < Knockapi::BaseModel
          attr_reader filter: String?

          def filter=: (String) -> String

          attr_reader select_: String?

          def select_=: (String) -> String

          attr_reader skiptoken: String?

          def skiptoken=: (String) -> String

          attr_reader top: Integer?

          def top=: (Integer) -> Integer

          def initialize: (
            ?filter: String,
            ?select_: String,
            ?skiptoken: String,
            ?top: Integer
          ) -> void

          def to_hash: -> Knockapi::Models::Providers::MsTeamListTeamsParams::query_options
        end
      end
    end
  end
end
