module Knockapi
  module Models
    module Providers
      type slack_check_auth_params =
        { access_token_object: String }
        & Knockapi::Internal::Type::request_parameters

      class SlackCheckAuthParams < Knockapi::BaseModel
        extend Knockapi::Internal::Type::RequestParameters::Converter
        include Knockapi::Internal::Type::RequestParameters

        attr_accessor access_token_object: String

        def initialize: (
          access_token_object: String,
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> Knockapi::Models::Providers::slack_check_auth_params
      end
    end
  end
end
