module Knockapi
  module Models
    module Providers
      type slack_check_auth_response =
        {
          connection: Knockapi::Models::Providers::SlackCheckAuthResponse::Connection
        }

      class SlackCheckAuthResponse < Knockapi::Internal::Type::BaseModel
        attr_accessor connection: Knockapi::Models::Providers::SlackCheckAuthResponse::Connection

        def initialize: (
          connection: Knockapi::Models::Providers::SlackCheckAuthResponse::Connection
        ) -> void

        type connection = { ok: bool, reason: String? }

        class Connection < Knockapi::Internal::Type::BaseModel
          attr_accessor ok: bool

          attr_accessor reason: String?

          def initialize: (ok: bool, ?reason: String?) -> void
        end
      end
    end
  end
end
