module Knockapi
  module Models
    module Providers
      type slack_list_channels_params =
        {
          access_token_object: String,
          query_options: Knockapi::Models::Providers::SlackListChannelsParams::QueryOptions
        }
        & Knockapi::request_parameters

      class SlackListChannelsParams < Knockapi::BaseModel
        extend Knockapi::RequestParameters::Converter
        include Knockapi::RequestParameters

        attr_accessor access_token_object: String

        attr_reader query_options: Knockapi::Models::Providers::SlackListChannelsParams::QueryOptions?

        def query_options=: (
          Knockapi::Models::Providers::SlackListChannelsParams::QueryOptions
        ) -> Knockapi::Models::Providers::SlackListChannelsParams::QueryOptions

        def initialize: (
          access_token_object: String,
          ?query_options: Knockapi::Models::Providers::SlackListChannelsParams::QueryOptions,
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> Knockapi::Models::Providers::slack_list_channels_params

        type query_options =
          {
            cursor: String,
            exclude_archived: bool,
            limit: Integer,
            team_id: String,
            types: String
          }

        class QueryOptions < Knockapi::BaseModel
          attr_reader cursor: String?

          def cursor=: (String) -> String

          attr_reader exclude_archived: bool?

          def exclude_archived=: (bool) -> bool

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader team_id: String?

          def team_id=: (String) -> String

          attr_reader types: String?

          def types=: (String) -> String

          def initialize: (
            ?cursor: String,
            ?exclude_archived: bool,
            ?limit: Integer,
            ?team_id: String,
            ?types: String
          ) -> void

          def to_hash: -> Knockapi::Models::Providers::SlackListChannelsParams::query_options
        end
      end
    end
  end
end
