module Knockapi
  module Resources
    class Messages
      class Activities
        def list: (
          String message_id,
          ?after: String,
          ?before: String,
          ?page_size: Integer,
          ?trigger_data: String,
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::Internal::ItemsCursor[Knockapi::Activity]

        def initialize: (client: Knockapi::Client) -> void
      end
    end
  end
end
