module Knock
  module Models
    module Objects
      type bulk_delete_params =
        { object_ids: ::Array[String] } & Knock::request_parameters

      class BulkDeleteParams < Knock::BaseModel
        extend Knock::RequestParameters::Converter
        include Knock::RequestParameters

        attr_accessor object_ids: ::Array[String]

        def initialize:
          (
            object_ids: ::Array[String],
            request_options: Knock::request_opts
          ) -> void
          | (
            ?Knock::Models::Objects::bulk_delete_params | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Objects::bulk_delete_params
      end
    end
  end
end
