module Knock
  module Models
    module Objects
      type bulk_set_params =
        { objects: ::Array[Knock::Models::InlineObjectRequest] }
        & Knock::request_parameters

      class BulkSetParams < Knock::BaseModel
        extend Knock::RequestParameters::Converter
        include Knock::RequestParameters

        attr_accessor objects: ::Array[Knock::Models::InlineObjectRequest]

        def initialize:
          (
            objects: ::Array[Knock::Models::InlineObjectRequest],
            request_options: Knock::request_opts
          ) -> void
          | (
            ?Knock::Models::Objects::bulk_set_params | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Objects::bulk_set_params
      end
    end
  end
end
