module Knockapi
  module Resources
    class Tenants
      class Bulk
        def delete: (
          tenant_ids: ::Array[String],
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::BulkOperation

        def set: (
          tenants: ::Array[Knockapi::Models::inline_tenant_request],
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::BulkOperation

        def initialize: (client: Knockapi::Client) -> void
      end
    end
  end
end
