module Knockapi
  module Models
    module Tenants
      type bulk_set_params =
        { tenants: ::Array[Knockapi::Models::inline_tenant_request] }
        & Knockapi::request_parameters

      class BulkSetParams < Knockapi::BaseModel
        extend Knockapi::RequestParameters::Converter
        include Knockapi::RequestParameters

        attr_accessor tenants: ::Array[Knockapi::Models::inline_tenant_request]

        def initialize: (
          tenants: ::Array[Knockapi::Models::inline_tenant_request],
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> Knockapi::Models::Tenants::bulk_set_params
      end
    end
  end
end
