module Knockapi
  module Models
    module Tenants
      type bulk_delete_params =
        { tenant_ids: ::Array[String] } & Knockapi::request_parameters

      class BulkDeleteParams < Knockapi::BaseModel
        extend Knockapi::RequestParameters::Converter
        include Knockapi::RequestParameters

        attr_accessor tenant_ids: ::Array[String]

        def initialize:
          (
            tenant_ids: ::Array[String],
            request_options: Knockapi::request_opts
          ) -> void
          | (
            ?Knockapi::Models::Tenants::bulk_delete_params
            | Knockapi::BaseModel data
          ) -> void

        def to_hash: -> Knockapi::Models::Tenants::bulk_delete_params
      end
    end
  end
end
