module Knockapi
  module Resources
    class Users
      class Bulk
        def delete: (
          user_ids: ::Array[String],
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::BulkOperation

        def identify: (
          users: ::Array[Knockapi::InlineIdentifyUserRequest],
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::BulkOperation

        def set_preferences: (
          preferences: Knockapi::Recipients::PreferenceSetRequest,
          user_ids: ::Array[String],
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::BulkOperation

        def initialize: (client: Knockapi::Client) -> void
      end
    end
  end
end
