module Knockapi
  module Resources
    class Users
      class Bulk
        def delete:
          (
            Knockapi::Models::Users::BulkDeleteParams
            | ::Hash[Symbol, top] params
          ) -> Knockapi::Models::BulkOperation
          | (
            user_ids: ::Array[String],
            request_options: Knockapi::request_opts
          ) -> Knockapi::Models::BulkOperation

        def identify:
          (
            Knockapi::Models::Users::BulkIdentifyParams
            | ::Hash[Symbol, top] params
          ) -> Knockapi::Models::BulkOperation
          | (
            users: ::Array[Knockapi::Models::InlineIdentifyUserRequest],
            request_options: Knockapi::request_opts
          ) -> Knockapi::Models::BulkOperation

        def set_preferences:
          (
            Knockapi::Models::Users::BulkSetPreferencesParams
            | ::Hash[Symbol, top] params
          ) -> Knockapi::Models::BulkOperation
          | (
            preferences: Knockapi::Models::Recipients::PreferenceSetRequest,
            user_ids: ::Array[String],
            request_options: Knockapi::request_opts
          ) -> Knockapi::Models::BulkOperation

        def initialize: (client: Knockapi::Client) -> void
      end
    end
  end
end
