module Knock
  module Models
    module Tenants
      type bulk_set_params =
        { tenants: ::Array[Knock::Models::inline_tenant_request] }
        & Knock::request_parameters

      class BulkSetParams < Knock::BaseModel
        extend Knock::RequestParameters::Converter
        include Knock::RequestParameters

        attr_accessor tenants: ::Array[Knock::Models::inline_tenant_request]

        def initialize:
          (
            tenants: ::Array[Knock::Models::inline_tenant_request],
            request_options: Knock::request_opts
          ) -> void
          | (
            ?Knock::Models::Tenants::bulk_set_params | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Tenants::bulk_set_params
      end
    end
  end
end
