module Knockapi
  module Models
    type audience_member =
      {
        _typename: String,
        added_at: Time,
        user: Knockapi::User,
        user_id: String,
        tenant: String?
      }

    class AudienceMember < Knockapi::Internal::Type::BaseModel
      attr_accessor _typename: String

      attr_accessor added_at: Time

      attr_accessor user: Knockapi::User

      attr_accessor user_id: String

      attr_accessor tenant: String?

      def initialize: (
        _typename: String,
        added_at: Time,
        user: Knockapi::User,
        user_id: String,
        ?tenant: String?
      ) -> void
    end
  end
end
