module Knockapi
  module Models
    type audience_remove_members_params =
      { members: ::Array[Knockapi::AudienceRemoveMembersParams::Member] }
      & Knockapi::Internal::Type::request_parameters

    class AudienceRemoveMembersParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor members: ::Array[Knockapi::AudienceRemoveMembersParams::Member]

      def initialize: (
        members: ::Array[Knockapi::AudienceRemoveMembersParams::Member],
        ?request_options: Knockapi::request_opts
      ) -> void

      type member =
        {
          user: Knockapi::AudienceRemoveMembersParams::Member::User,
          tenant: String?
        }

      class Member < Knockapi::Internal::Type::BaseModel
        attr_accessor user: Knockapi::AudienceRemoveMembersParams::Member::User

        attr_accessor tenant: String?

        def initialize: (
          user: Knockapi::AudienceRemoveMembersParams::Member::User,
          ?tenant: String?
        ) -> void

        type user = { id: String }

        class User < Knockapi::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          def initialize: (?id: String) -> void
        end
      end
    end
  end
end
