module Knockapi
  module Models
    type audience_remove_members_params =
      {
        members: ::Array[Knockapi::Models::AudienceRemoveMembersParams::Member]
      }
      & Knockapi::Internal::Type::request_parameters

    class AudienceRemoveMembersParams < Knockapi::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor members: ::Array[Knockapi::Models::AudienceRemoveMembersParams::Member]

      def initialize: (
        members: ::Array[Knockapi::Models::AudienceRemoveMembersParams::Member],
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> Knockapi::Models::audience_remove_members_params

      type member =
        { user: Knockapi::Models::InlineIdentifyUserRequest, tenant: String? }

      class Member < Knockapi::BaseModel
        attr_accessor user: Knockapi::Models::InlineIdentifyUserRequest

        attr_accessor tenant: String?

        def initialize: (
          user: Knockapi::Models::InlineIdentifyUserRequest,
          ?tenant: String?
        ) -> void

        def to_hash: -> Knockapi::Models::AudienceRemoveMembersParams::member
      end
    end
  end
end
