module Knockapi
  module Models
    type audience_list_members_response =
      {
        entries: ::Array[Knockapi::AudienceMember],
        page_info: Knockapi::PageInfo
      }

    class AudienceListMembersResponse < Knockapi::Internal::Type::BaseModel
      attr_accessor entries: ::Array[Knockapi::AudienceMember]

      attr_accessor page_info: Knockapi::PageInfo

      def initialize: (
        entries: ::Array[Knockapi::AudienceMember],
        page_info: Knockapi::PageInfo
      ) -> void
    end
  end
end
