module Knockapi
  module Models
    type audience_add_members_params =
      { members: ::Array[Knockapi::AudienceAddMembersParams::Member] }
      & Knockapi::Internal::Type::request_parameters

    class AudienceAddMembersParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor members: ::Array[Knockapi::AudienceAddMembersParams::Member]

      def initialize: (
        members: ::Array[Knockapi::AudienceAddMembersParams::Member],
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        members: ::Array[Knockapi::AudienceAddMembersParams::Member],
        request_options: Knockapi::RequestOptions
      }

      type member =
        { user: Knockapi::InlineIdentifyUserRequest, tenant: String? }

      class Member < Knockapi::Internal::Type::BaseModel
        attr_accessor user: Knockapi::InlineIdentifyUserRequest

        attr_accessor tenant: String?

        def initialize: (
          user: Knockapi::InlineIdentifyUserRequest,
          ?tenant: String?
        ) -> void

        def to_hash: -> {
          user: Knockapi::InlineIdentifyUserRequest,
          tenant: String?
        }
      end
    end
  end
end
