module Knockapi
  module Models
    type audience_add_members_params =
      {
        key: String,
        members: ::Array[Knockapi::AudienceMemberRequest],
        create_audience: bool
      }
      & Knockapi::Internal::Type::request_parameters

    class AudienceAddMembersParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor key: String

      attr_accessor members: ::Array[Knockapi::AudienceMemberRequest]

      attr_reader create_audience: bool?

      def create_audience=: (bool) -> bool

      def initialize: (
        key: String,
        members: ::Array[Knockapi::AudienceMemberRequest],
        ?create_audience: bool,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        key: String,
        members: ::Array[Knockapi::AudienceMemberRequest],
        create_audience: bool,
        request_options: Knockapi::RequestOptions
      }
    end
  end
end
