module Knockapi
  module Models
    type bulk_operation_get_params = {  } & Knockapi::request_parameters

    class BulkOperationGetParams < Knockapi::BaseModel
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::bulk_operation_get_params
    end
  end
end
