module Knockapi
  module Models
    type inline_object_request =
      {
        id: String,
        channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        collection: String,
        created_at: Time?,
        preferences: Knockapi::Models::Recipients::inline_preference_set_request?
      }

    class InlineObjectRequest < Knockapi::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_accessor channel_data: Knockapi::Models::Recipients::inline_channel_data_request?

      attr_reader collection: String?

      def collection=: (String) -> String

      attr_accessor created_at: Time?

      attr_accessor preferences: Knockapi::Models::Recipients::inline_preference_set_request?

      def initialize: (
        ?id: String,
        ?channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        ?collection: String,
        ?created_at: Time?,
        ?preferences: Knockapi::Models::Recipients::inline_preference_set_request?
      ) -> void

      def to_hash: -> Knockapi::Models::inline_object_request
    end
  end
end
