module Knockapi
  module Models
    type inline_tenant_request = String | Knockapi::Models::TenantRequest

    class InlineTenantRequest < Knockapi::Union
      def self.variants: -> [String, Knockapi::Models::TenantRequest]
    end
  end
end
