module Knockapi
  module Models
    type inline_object_request =
      {
        id: String,
        collection: String,
        channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        created_at: Time?,
        preferences: ::Array[Knockapi::Models::Recipients::InlinePreferenceSetRequest]?
      }

    class InlineObjectRequest < Knockapi::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor collection: String

      attr_accessor channel_data: Knockapi::Models::Recipients::inline_channel_data_request?

      attr_accessor created_at: Time?

      attr_accessor preferences: ::Array[Knockapi::Models::Recipients::InlinePreferenceSetRequest]?

      def initialize: (
        id: String,
        collection: String,
        ?channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        ?created_at: Time?,
        ?preferences: ::Array[Knockapi::Models::Recipients::InlinePreferenceSetRequest]?
      ) -> void

      def to_hash: -> Knockapi::Models::inline_object_request
    end
  end
end
