module Knockapi
  module Models
    type inline_identify_user_request =
      {
        id: String,
        channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        created_at: Time?,
        preferences: Knockapi::Models::Recipients::inline_preference_set_request?
      }

    class InlineIdentifyUserRequest < Knockapi::BaseModel
      attr_accessor id: String

      attr_accessor channel_data: Knockapi::Models::Recipients::inline_channel_data_request?

      attr_accessor created_at: Time?

      attr_accessor preferences: Knockapi::Models::Recipients::inline_preference_set_request?

      def initialize:
        (
          id: String,
          ?channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
          ?created_at: Time?,
          ?preferences: Knockapi::Models::Recipients::inline_preference_set_request?
        ) -> void
        | (
          ?Knockapi::Models::inline_identify_user_request
          | Knockapi::BaseModel data
        ) -> void

      def to_hash: -> Knockapi::Models::inline_identify_user_request
    end
  end
end
