module Knockapi
  module Models
    type list_schedules_response =
      { entries: ::Array[Knockapi::Schedule], page_info: Knockapi::PageInfo }

    class ListSchedulesResponse < Knockapi::Internal::Type::BaseModel
      attr_accessor entries: ::Array[Knockapi::Schedule]

      attr_accessor page_info: Knockapi::PageInfo

      def initialize: (
        entries: ::Array[Knockapi::Schedule],
        page_info: Knockapi::PageInfo
      ) -> void

      def to_hash: -> {
        entries: ::Array[Knockapi::Schedule],
        page_info: Knockapi::PageInfo
      }
    end
  end
end
