module Knockapi
  module Models
    type message_mark_as_interacted_params =
      { metadata: ::Hash[Symbol, top] } & Knockapi::request_parameters

    class MessageMarkAsInteractedParams < Knockapi::BaseModel
      extend Knockapi::Type::RequestParameters::Converter
      include Knockapi::RequestParameters

      attr_reader metadata: ::Hash[Symbol, top]?

      def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        ?metadata: ::Hash[Symbol, top],
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> Knockapi::Models::message_mark_as_interacted_params
    end
  end
end
