module Knockapi
  module Models
    type message_mark_as_unread_params = {  } & Knockapi::request_parameters

    class MessageMarkAsUnreadParams < Knockapi::BaseModel
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::message_mark_as_unread_params
    end
  end
end
