module Knockapi
  module Models
    type message_get_content_params = {  } & Knockapi::request_parameters

    class MessageGetContentParams < Knockapi::BaseModel
      extend Knockapi::Type::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::message_get_content_params
    end
  end
end
