module Knockapi
  module Models
    type message_mark_as_read_params = {  } & Knockapi::request_parameters

    class MessageMarkAsReadParams < Knockapi::BaseModel
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize:
        (?request_options: Knockapi::request_opts) -> void
        | (
          ?Knockapi::Models::message_mark_as_read_params
          | Knockapi::BaseModel data
        ) -> void

      def to_hash: -> Knockapi::Models::message_mark_as_read_params
    end
  end
end
