module Knockapi
  module Models
    type message_mark_as_seen_params =
      {  } & Knockapi::Internal::Type::request_parameters

    class MessageMarkAsSeenParams < Knockapi::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::message_mark_as_seen_params
    end
  end
end
