module Knockapi
  module Models
    type object_list_subscriptions_params =
      {
        after: String,
        before: String,
        mode: Knockapi::Models::ObjectListSubscriptionsParams::mode,
        objects: ::Array[Knockapi::Models::ObjectListSubscriptionsParams::object],
        page_size: Integer,
        recipients: ::Array[Knockapi::Models::ObjectListSubscriptionsParams::recipient]
      }
      & Knockapi::Internal::Type::request_parameters

    class ObjectListSubscriptionsParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader mode: Knockapi::Models::ObjectListSubscriptionsParams::mode?

      def mode=: (
        Knockapi::Models::ObjectListSubscriptionsParams::mode
      ) -> Knockapi::Models::ObjectListSubscriptionsParams::mode

      attr_reader objects: ::Array[Knockapi::Models::ObjectListSubscriptionsParams::object]?

      def objects=: (
        ::Array[Knockapi::Models::ObjectListSubscriptionsParams::object]
      ) -> ::Array[Knockapi::Models::ObjectListSubscriptionsParams::object]

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader recipients: ::Array[Knockapi::Models::ObjectListSubscriptionsParams::recipient]?

      def recipients=: (
        ::Array[Knockapi::Models::ObjectListSubscriptionsParams::recipient]
      ) -> ::Array[Knockapi::Models::ObjectListSubscriptionsParams::recipient]

      def initialize: (
        ?after: String,
        ?before: String,
        ?mode: Knockapi::Models::ObjectListSubscriptionsParams::mode,
        ?objects: ::Array[Knockapi::Models::ObjectListSubscriptionsParams::object],
        ?page_size: Integer,
        ?recipients: ::Array[Knockapi::Models::ObjectListSubscriptionsParams::recipient],
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> Knockapi::Models::object_list_subscriptions_params

      type mode = :recipient | :object

      module Mode
        extend Knockapi::Internal::Type::Enum

        RECIPIENT: :recipient
        OBJECT: :object

        def self?.values: -> ::Array[Knockapi::Models::ObjectListSubscriptionsParams::mode]
      end

      type object =
        String
        | Knockapi::Models::ObjectListSubscriptionsParams::Object::UnionMember1

      module Object
        extend Knockapi::Internal::Type::Union

        type union_member1 = { id: String, collection: String }

        class UnionMember1 < Knockapi::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor collection: String

          def initialize: (id: String, collection: String) -> void

          def to_hash: -> Knockapi::Models::ObjectListSubscriptionsParams::Object::union_member1
        end

        def self?.variants: -> [String, Knockapi::Models::ObjectListSubscriptionsParams::Object::UnionMember1]
      end

      type recipient =
        String
        | Knockapi::Models::ObjectListSubscriptionsParams::Recipient::UnionMember1

      module Recipient
        extend Knockapi::Internal::Type::Union

        type union_member1 = { id: String, collection: String }

        class UnionMember1 < Knockapi::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor collection: String

          def initialize: (id: String, collection: String) -> void

          def to_hash: -> Knockapi::Models::ObjectListSubscriptionsParams::Recipient::union_member1
        end

        def self?.variants: -> [String, Knockapi::Models::ObjectListSubscriptionsParams::Recipient::UnionMember1]
      end
    end
  end
end
