module Knockapi
  module Models
    type object_list_preferences_response =
      ::Array[Knockapi::Recipients::PreferenceSet]

    ObjectListPreferencesResponse: Knockapi::Internal::Type::Converter
  end
end
