module Knockapi
  module Models
    type object =
      {
        id: String,
        _typename: String,
        collection: String,
        updated_at: Time,
        created_at: Time?,
        properties: ::Hash[Symbol, top]
      }

    class Object < Knockapi::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor _typename: String

      attr_accessor collection: String

      attr_accessor updated_at: Time

      attr_accessor created_at: Time?

      attr_reader properties: ::Hash[Symbol, top]?

      def properties=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        id: String,
        _typename: String,
        collection: String,
        updated_at: Time,
        ?created_at: Time?,
        ?properties: ::Hash[Symbol, top]
      ) -> void
    end
  end
end
