module Knockapi
  module Models
    type object_set_preferences_params =
      {  } & Knockapi::Internal::Type::request_parameters

    class ObjectSetPreferencesParams < Knockapi::Models::Recipients::PreferenceSetRequest
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::object_set_preferences_params
    end
  end
end
