module Knockapi
  module Models
    type object_delete_subscriptions_response =
      ::Array[Knockapi::Recipients::Subscription]

    ObjectDeleteSubscriptionsResponse: Knockapi::Internal::Type::Converter
  end
end
