module Knockapi
  module Models
    type object =
      {
        id: String,
        _typename: String,
        collection: String,
        updated_at: Time,
        created_at: Time?
      }

    class Object < Knockapi::BaseModel
      attr_accessor id: String

      attr_accessor _typename: String

      attr_accessor collection: String

      attr_accessor updated_at: Time

      attr_accessor created_at: Time?

      def initialize: (
        id: String,
        _typename: String,
        collection: String,
        updated_at: Time,
        ?created_at: Time?
      ) -> void

      def to_hash: -> Knockapi::Models::object
    end
  end
end
