module Knockapi
  module Models
    type object_list_schedules_params =
      {
        after: String,
        before: String,
        page_size: Integer,
        tenant: String,
        workflow: String
      }
      & Knockapi::Internal::Type::request_parameters

    class ObjectListSchedulesParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader tenant: String?

      def tenant=: (String) -> String

      attr_reader workflow: String?

      def workflow=: (String) -> String

      def initialize: (
        ?after: String,
        ?before: String,
        ?page_size: Integer,
        ?tenant: String,
        ?workflow: String,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> Knockapi::Models::object_list_schedules_params
    end
  end
end
