module Knockapi
  module Models
    type object_add_subscriptions_params =
      {
        recipients: ::Array[Knockapi::Models::recipient_request],
        properties: ::Hash[Symbol, top]?
      }
      & Knockapi::request_parameters

    class ObjectAddSubscriptionsParams < Knockapi::BaseModel
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      attr_accessor recipients: ::Array[Knockapi::Models::recipient_request]

      attr_accessor properties: ::Hash[Symbol, top]?

      def initialize:
        (
          recipients: ::Array[Knockapi::Models::recipient_request],
          properties: ::Hash[Symbol, top]?,
          request_options: Knockapi::request_opts
        ) -> void
        | (
          ?Knockapi::Models::object_add_subscriptions_params
          | Knockapi::BaseModel data
        ) -> void

      def to_hash: -> Knockapi::Models::object_add_subscriptions_params
    end
  end
end
