module Knockapi
  module Models
    type object_add_subscriptions_params =
      {
        recipients: ::Array[Knockapi::Models::recipient_request],
        properties: ::Hash[Symbol, top]?
      }
      & Knockapi::Internal::Type::request_parameters

    class ObjectAddSubscriptionsParams < Knockapi::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor recipients: ::Array[Knockapi::Models::recipient_request]

      attr_accessor properties: ::Hash[Symbol, top]?

      def initialize: (
        recipients: ::Array[Knockapi::Models::recipient_request],
        ?properties: ::Hash[Symbol, top]?,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> Knockapi::Models::object_add_subscriptions_params
    end
  end
end
