module Knockapi
  module Models
    type object_delete_params = {  } & Knockapi::request_parameters

    class ObjectDeleteParams < Knockapi::BaseModel
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::object_delete_params
    end
  end
end
