module Knockapi
  module Models
    type object_get_params =
      { collection: String, id: String }
      & Knockapi::Internal::Type::request_parameters

    class ObjectGetParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor collection: String

      attr_accessor id: String

      def initialize: (
        collection: String,
        id: String,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        collection: String,
        id: String,
        request_options: Knockapi::RequestOptions
      }
    end
  end
end
