module Knockapi
  module Models
    type object_set_preferences_params = {  } & Knockapi::request_parameters

    class ObjectSetPreferencesParams < Knockapi::Models::Recipients::PreferenceSetRequest
      extend Knockapi::Type::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::object_set_preferences_params
    end
  end
end
