module Knockapi
  module Models
    type object_get_preferences_params =
      { tenant: String } & Knockapi::request_parameters

    class ObjectGetPreferencesParams < Knockapi::BaseModel
      extend Knockapi::Type::RequestParameters::Converter
      include Knockapi::RequestParameters

      attr_reader tenant: String?

      def tenant=: (String) -> String

      def initialize: (
        ?tenant: String,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> Knockapi::Models::object_get_preferences_params
    end
  end
end
