module Knockapi
  module Models
    type object_set_params =
      {
        channel_data: Knockapi::Models::Recipients::inline_channel_data_request,
        locale: String?,
        preferences: Knockapi::Models::Recipients::inline_preference_set_request,
        timezone: String?
      }
      & Knockapi::Internal::Type::request_parameters

    class ObjectSetParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_reader channel_data: Knockapi::Models::Recipients::inline_channel_data_request?

      def channel_data=: (
        Knockapi::Models::Recipients::inline_channel_data_request
      ) -> Knockapi::Models::Recipients::inline_channel_data_request

      attr_accessor locale: String?

      attr_reader preferences: Knockapi::Models::Recipients::inline_preference_set_request?

      def preferences=: (
        Knockapi::Models::Recipients::inline_preference_set_request
      ) -> Knockapi::Models::Recipients::inline_preference_set_request

      attr_accessor timezone: String?

      def initialize: (
        ?channel_data: Knockapi::Models::Recipients::inline_channel_data_request,
        ?locale: String?,
        ?preferences: Knockapi::Models::Recipients::inline_preference_set_request,
        ?timezone: String?,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        channel_data: Knockapi::Models::Recipients::inline_channel_data_request,
        locale: String?,
        preferences: Knockapi::Models::Recipients::inline_preference_set_request,
        timezone: String?,
        request_options: Knockapi::RequestOptions
      }
    end
  end
end
