module Knockapi
  module Models
    type object_add_subscriptions_response =
      ::Array[Knockapi::Recipients::Subscription]

    ObjectAddSubscriptionsResponse: Knockapi::Internal::Type::Converter
  end
end
