module Knockapi
  module Models
    type preference_set_commercial_subscribed_setting =
      { conditions: ::Array[Knockapi::Condition] }

    class PreferenceSetCommercialSubscribedSetting < Knockapi::Internal::Type::BaseModel
      attr_accessor conditions: ::Array[Knockapi::Condition]

      def initialize: (conditions: ::Array[Knockapi::Condition]) -> void

      def to_hash: -> { conditions: ::Array[Knockapi::Condition] }
    end
  end
end
