module Knockapi
  module Models
    type recipient = Knockapi::User | Knockapi::Object

    module Recipient
      extend Knockapi::Internal::Type::Union

      def self?.variants: -> ::Array[Knockapi::Models::recipient]
    end
  end
end
