module Knockapi
  module Models
    type recipient_request =
      String
      | Knockapi::Models::InlineIdentifyUserRequest
      | Knockapi::Models::InlineObjectRequest

    class RecipientRequest < Knockapi::Union
      private def self.variants: -> [[nil, String], [nil, Knockapi::Models::InlineIdentifyUserRequest], [nil, Knockapi::Models::InlineObjectRequest]]
    end
  end
end
