module Knockapi
  module Models
    type recipient_reference =
      String | Knockapi::RecipientReference::ObjectReference

    module RecipientReference
      extend Knockapi::Internal::Type::Union

      type object_reference = { id: String, collection: String }

      class ObjectReference < Knockapi::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader collection: String?

        def collection=: (String) -> String

        def initialize: (?id: String, ?collection: String) -> void

        def to_hash: -> { id: String, collection: String }
      end

      def self?.variants: -> ::Array[Knockapi::Models::recipient_reference]
    end
  end
end
