module Knockapi
  module Models
    type recipient = Knockapi::Models::User | Knockapi::Models::Object

    module Recipient
      extend Knockapi::Union

      def self?.variants: -> [Knockapi::Models::User, Knockapi::Models::Object]
    end
  end
end
