module Knockapi
  module Models
    type schedule_list_params =
      {
        workflow: String,
        after: String,
        before: String,
        page_size: Integer,
        recipients: ::Array[Knockapi::Models::ScheduleListParams::recipient],
        tenant: String
      }
      & Knockapi::request_parameters

    class ScheduleListParams < Knockapi::BaseModel
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      attr_accessor workflow: String

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader recipients: ::Array[Knockapi::Models::ScheduleListParams::recipient]?

      def recipients=: (
        ::Array[Knockapi::Models::ScheduleListParams::recipient]
      ) -> ::Array[Knockapi::Models::ScheduleListParams::recipient]

      attr_reader tenant: String?

      def tenant=: (String) -> String

      def initialize:
        (
          workflow: String,
          after: String,
          before: String,
          page_size: Integer,
          recipients: ::Array[Knockapi::Models::ScheduleListParams::recipient],
          tenant: String,
          request_options: Knockapi::request_opts
        ) -> void
        | (
          ?Knockapi::Models::schedule_list_params | Knockapi::BaseModel data
        ) -> void

      def to_hash: -> Knockapi::Models::schedule_list_params

      type recipient =
        String
        | Knockapi::Models::ScheduleListParams::Recipient::ObjectReference

      class Recipient < Knockapi::Union
        type object_reference = { id: String, collection: String }

        class ObjectReference < Knockapi::BaseModel
          attr_accessor id: String

          attr_accessor collection: String

          def initialize:
            (id: String, collection: String) -> void
            | (
              ?Knockapi::Models::ScheduleListParams::Recipient::object_reference
              | Knockapi::BaseModel data
            ) -> void

          def to_hash: -> Knockapi::Models::ScheduleListParams::Recipient::object_reference
        end

        def self.variants: -> [String, Knockapi::Models::ScheduleListParams::Recipient::ObjectReference]
      end
    end
  end
end
