module Knockapi
  module Models
    type schedule_delete_params =
      {  } & Knockapi::Internal::Type::request_parameters

    class ScheduleDeleteParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::schedule_delete_params
    end
  end
end
