module Knockapi
  module Models
    type tenant_set_params =
      {
        resolve_full_preference_settings: bool,
        channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        name: String?,
        settings: Knockapi::TenantSetParams::Settings
      }
      & Knockapi::Internal::Type::request_parameters

    class TenantSetParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_reader resolve_full_preference_settings: bool?

      def resolve_full_preference_settings=: (bool) -> bool

      attr_accessor channel_data: Knockapi::Models::Recipients::inline_channel_data_request?

      attr_accessor name: String?

      attr_reader settings: Knockapi::TenantSetParams::Settings?

      def settings=: (
        Knockapi::TenantSetParams::Settings
      ) -> Knockapi::TenantSetParams::Settings

      def initialize: (
        ?resolve_full_preference_settings: bool,
        ?channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        ?name: String?,
        ?settings: Knockapi::TenantSetParams::Settings,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        resolve_full_preference_settings: bool,
        channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        name: String?,
        settings: Knockapi::TenantSetParams::Settings,
        request_options: Knockapi::RequestOptions
      }

      type settings =
        {
          branding: Knockapi::TenantSetParams::Settings::Branding,
          preference_set: Knockapi::Recipients::PreferenceSetRequest?
        }

      class Settings < Knockapi::Internal::Type::BaseModel
        attr_reader branding: Knockapi::TenantSetParams::Settings::Branding?

        def branding=: (
          Knockapi::TenantSetParams::Settings::Branding
        ) -> Knockapi::TenantSetParams::Settings::Branding

        attr_accessor preference_set: Knockapi::Recipients::PreferenceSetRequest?

        def initialize: (
          ?branding: Knockapi::TenantSetParams::Settings::Branding,
          ?preference_set: Knockapi::Recipients::PreferenceSetRequest?
        ) -> void

        def to_hash: -> {
          branding: Knockapi::TenantSetParams::Settings::Branding,
          preference_set: Knockapi::Recipients::PreferenceSetRequest?
        }

        type branding =
          {
            icon_url: String?,
            logo_url: String?,
            primary_color: String?,
            primary_color_contrast: String?
          }

        class Branding < Knockapi::Internal::Type::BaseModel
          attr_accessor icon_url: String?

          attr_accessor logo_url: String?

          attr_accessor primary_color: String?

          attr_accessor primary_color_contrast: String?

          def initialize: (
            ?icon_url: String?,
            ?logo_url: String?,
            ?primary_color: String?,
            ?primary_color_contrast: String?
          ) -> void

          def to_hash: -> {
            icon_url: String?,
            logo_url: String?,
            primary_color: String?,
            primary_color_contrast: String?
          }
        end
      end
    end
  end
end
