module Knockapi
  module Models
    type tenant = { id: String, _typename: String }

    class Tenant < Knockapi::BaseModel
      attr_accessor id: String

      attr_accessor _typename: String

      def initialize:
        (id: String, _typename: String) -> void
        | (?Knockapi::Models::tenant | Knockapi::BaseModel data) -> void

      def to_hash: -> Knockapi::Models::tenant
    end
  end
end
