module Knockapi
  module Models
    type tenant =
      { id: String, _typename: String, name: String?, settings: top? }

    class Tenant < Knockapi::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor _typename: String

      attr_accessor name: String?

      attr_accessor settings: top?

      def initialize: (
        id: String,
        _typename: String,
        ?name: String?,
        ?settings: top?
      ) -> void

      def to_hash: -> Knockapi::Models::tenant
    end
  end
end
