module Knockapi
  module Models
    type user_set_channel_data_params =
      { user_id: String, channel_id: String }
      & Knockapi::Internal::Type::request_parameters

    class UserSetChannelDataParams < Knockapi::Models::Recipients::ChannelDataRequest
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      def user_id: -> String

      def user_id=: (String _) -> String

      def channel_id: -> String

      def channel_id=: (String _) -> String

      def initialize: (
        user_id: String,
        channel_id: String,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        user_id: String,
        channel_id: String,
        request_options: Knockapi::RequestOptions
      }
    end
  end
end
