module Knockapi
  module Models
    type user_list_subscriptions_params =
      {
        after: String,
        before: String,
        include: ::Array[Knockapi::UserListSubscriptionsParams::include_],
        objects: ::Array[String],
        page_size: Integer
      }
      & Knockapi::Internal::Type::request_parameters

    class UserListSubscriptionsParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader include: ::Array[Knockapi::UserListSubscriptionsParams::include_]?

      def include=: (
        ::Array[Knockapi::UserListSubscriptionsParams::include_]
      ) -> ::Array[Knockapi::UserListSubscriptionsParams::include_]

      attr_reader objects: ::Array[String]?

      def objects=: (::Array[String]) -> ::Array[String]

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      def initialize: (
        ?after: String,
        ?before: String,
        ?include: ::Array[Knockapi::UserListSubscriptionsParams::include_],
        ?objects: ::Array[String],
        ?page_size: Integer,
        ?request_options: Knockapi::request_opts
      ) -> void

      type include_ = :preferences

      module Include
        extend Knockapi::Internal::Type::Enum

        PREFERENCES: :preferences

        def self?.values: -> ::Array[Knockapi::UserListSubscriptionsParams::include_]
      end
    end
  end
end
