module Knockapi
  module Models
    type user_update_response =
      {
        id: String,
        created_at: Time,
        updated_at: Time,
        _typename: String,
        avatar: String?,
        channel_data: ::Array[Knockapi::Models::Recipients::RecipientsChannelData]?,
        email: String?,
        locale: String?,
        name: String?,
        phone_number: String?,
        preferences: Knockapi::Models::Recipients::PreferenceSet?,
        timezone: String?
      }

    class UserUpdateResponse < Knockapi::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor updated_at: Time

      attr_reader _typename: String?

      def _typename=: (String) -> String

      attr_accessor avatar: String?

      attr_accessor channel_data: ::Array[Knockapi::Models::Recipients::RecipientsChannelData]?

      attr_accessor email: String?

      attr_accessor locale: String?

      attr_accessor name: String?

      attr_accessor phone_number: String?

      attr_accessor preferences: Knockapi::Models::Recipients::PreferenceSet?

      attr_accessor timezone: String?

      def initialize: (
        id: String,
        created_at: Time,
        updated_at: Time,
        ?_typename: String,
        ?avatar: String?,
        ?channel_data: ::Array[Knockapi::Models::Recipients::RecipientsChannelData]?,
        ?email: String?,
        ?locale: String?,
        ?name: String?,
        ?phone_number: String?,
        ?preferences: Knockapi::Models::Recipients::PreferenceSet?,
        ?timezone: String?
      ) -> void

      def to_hash: -> Knockapi::Models::user_update_response
    end
  end
end
