module Knockapi
  module Models
    type user_delete_params = {  } & Knockapi::request_parameters

    class UserDeleteParams < Knockapi::BaseModel
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize:
        (request_options: Knockapi::request_opts) -> void
        | (
          ?Knockapi::Models::user_delete_params | Knockapi::BaseModel data
        ) -> void

      def to_hash: -> Knockapi::Models::user_delete_params
    end
  end
end
