module Knockapi
  module Models
    type user_set_preferences_params = {  } & Knockapi::request_parameters

    class UserSetPreferencesParams < Knockapi::Models::Recipients::PreferenceSetRequest
      extend Knockapi::Type::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::user_set_preferences_params
    end
  end
end
