module Knockapi
  module Models
    type user_list_subscriptions_params =
      {
        after: String,
        before: String,
        include: ::Array[Knockapi::Models::UserListSubscriptionsParams::include_],
        objects: ::Array[Knockapi::Models::UserListSubscriptionsParams::object],
        page_size: Integer
      }
      & Knockapi::Internal::Type::request_parameters

    class UserListSubscriptionsParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader include: ::Array[Knockapi::Models::UserListSubscriptionsParams::include_]?

      def include=: (
        ::Array[Knockapi::Models::UserListSubscriptionsParams::include_]
      ) -> ::Array[Knockapi::Models::UserListSubscriptionsParams::include_]

      attr_reader objects: ::Array[Knockapi::Models::UserListSubscriptionsParams::object]?

      def objects=: (
        ::Array[Knockapi::Models::UserListSubscriptionsParams::object]
      ) -> ::Array[Knockapi::Models::UserListSubscriptionsParams::object]

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      def initialize: (
        ?after: String,
        ?before: String,
        ?include: ::Array[Knockapi::Models::UserListSubscriptionsParams::include_],
        ?objects: ::Array[Knockapi::Models::UserListSubscriptionsParams::object],
        ?page_size: Integer,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> Knockapi::Models::user_list_subscriptions_params

      type include_ = :preferences

      module Include
        extend Knockapi::Internal::Type::Enum

        PREFERENCES: :preferences

        def self?.values: -> ::Array[Knockapi::Models::UserListSubscriptionsParams::include_]
      end

      type object =
        String
        | Knockapi::Models::UserListSubscriptionsParams::Object::ObjectReference

      module Object
        extend Knockapi::Internal::Type::Union

        type object_reference = { id: String, collection: String }

        class ObjectReference < Knockapi::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor collection: String

          def initialize: (id: String, collection: String) -> void

          def to_hash: -> Knockapi::Models::UserListSubscriptionsParams::Object::object_reference
        end

        def self?.variants: -> [String, Knockapi::Models::UserListSubscriptionsParams::Object::ObjectReference]
      end
    end
  end
end
