module Knockapi
  module Models
    type user_update_params =
      { user_id: String } & Knockapi::Internal::Type::request_parameters

    class UserUpdateParams < Knockapi::Models::IdentifyUserRequest
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      def user_id: -> String

      def user_id=: (String _) -> String

      def initialize: (
        user_id: String,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        user_id: String,
        request_options: Knockapi::RequestOptions
      }
    end
  end
end
