module Knockapi
  module Models
    type user_unset_channel_data_params = {  } & Knockapi::request_parameters

    class UserUnsetChannelDataParams < Knockapi::BaseModel
      extend Knockapi::Type::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::user_unset_channel_data_params
    end
  end
end
