module Knockapi
  module Models
    type user_set_preferences_params = {  } & Knockapi::request_parameters

    class UserSetPreferencesParams < Knockapi::Models::Recipients::PreferenceSetRequest
      extend Knockapi::RequestParameters::Converter
      include Knockapi::RequestParameters

      def initialize:
        (?request_options: Knockapi::request_opts) -> void
        | (
          ?Knockapi::Models::user_set_preferences_params
          | Knockapi::BaseModel data
        ) -> void

      def to_hash: -> Knockapi::Models::user_set_preferences_params
    end
  end
end
