module Knockapi
  module Models
    type user_get_channel_data_params =
      {  } & Knockapi::Internal::Type::request_parameters

    class UserGetChannelDataParams < Knockapi::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void

      def to_hash: -> Knockapi::Models::user_get_channel_data_params
    end
  end
end
