module Knockapi
  module Models
    type user_list_preferences_response =
      ::Array[Knockapi::Models::Recipients::PreferenceSet]

    UserListPreferencesResponse: user_list_preferences_response
  end
end
