module Knockapi
  module Models
    type user_delete_params =
      { user_id: String } & Knockapi::Internal::Type::request_parameters

    class UserDeleteParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor user_id: String

      def initialize: (
        user_id: String,
        ?request_options: Knockapi::request_opts
      ) -> void

      def to_hash: -> {
        user_id: String,
        request_options: Knockapi::RequestOptions
      }
    end
  end
end
