module Knockapi
  module Models
    type user_update_params =
      {  } & Knockapi::Internal::Type::request_parameters

    class UserUpdateParams < Knockapi::Models::IdentifyUserRequest
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      def initialize: (?request_options: Knockapi::request_opts) -> void
    end
  end
end
