module Knockapi
  module Models
    type workflow_cancel_params =
      {
        cancellation_key: String,
        recipients: ::Array[Knockapi::Models::recipient_reference]?
      }
      & Knockapi::Internal::Type::request_parameters

    class WorkflowCancelParams < Knockapi::Internal::Type::BaseModel
      extend Knockapi::Internal::Type::RequestParameters::Converter
      include Knockapi::Internal::Type::RequestParameters

      attr_accessor cancellation_key: String

      attr_accessor recipients: ::Array[Knockapi::Models::recipient_reference]?

      def initialize: (
        cancellation_key: String,
        ?recipients: ::Array[Knockapi::Models::recipient_reference]?,
        ?request_options: Knockapi::request_opts
      ) -> void
    end
  end
end
