module Knockapi
  module Models
    module Schedules
      type bulk_create_schedules_request =
        {
          schedules: ::Array[Knockapi::Models::Schedules::BulkCreateSchedulesRequest::Schedule]
        }

      class BulkCreateSchedulesRequest < Knockapi::Internal::Type::BaseModel
        attr_accessor schedules: ::Array[Knockapi::Models::Schedules::BulkCreateSchedulesRequest::Schedule]

        def initialize: (
          schedules: ::Array[Knockapi::Models::Schedules::BulkCreateSchedulesRequest::Schedule]
        ) -> void

        def to_hash: -> Knockapi::Models::Schedules::bulk_create_schedules_request

        type schedule =
          {
            workflow: String,
            actor: Knockapi::Models::recipient_request?,
            data: ::Hash[Symbol, top]?,
            ending_at: Time?,
            recipient: Knockapi::Models::recipient_request,
            repeats: ::Array[Knockapi::Models::ScheduleRepeatRule],
            scheduled_at: Time?,
            tenant: Knockapi::Models::inline_tenant_request?
          }

        class Schedule < Knockapi::Internal::Type::BaseModel
          attr_accessor workflow: String

          attr_accessor actor: Knockapi::Models::recipient_request?

          attr_accessor data: ::Hash[Symbol, top]?

          attr_accessor ending_at: Time?

          attr_reader recipient: Knockapi::Models::recipient_request?

          def recipient=: (
            Knockapi::Models::recipient_request
          ) -> Knockapi::Models::recipient_request

          attr_reader repeats: ::Array[Knockapi::Models::ScheduleRepeatRule]?

          def repeats=: (
            ::Array[Knockapi::Models::ScheduleRepeatRule]
          ) -> ::Array[Knockapi::Models::ScheduleRepeatRule]

          attr_accessor scheduled_at: Time?

          attr_accessor tenant: Knockapi::Models::inline_tenant_request?

          def initialize: (
            workflow: String,
            ?actor: Knockapi::Models::recipient_request?,
            ?data: ::Hash[Symbol, top]?,
            ?ending_at: Time?,
            ?recipient: Knockapi::Models::recipient_request,
            ?repeats: ::Array[Knockapi::Models::ScheduleRepeatRule],
            ?scheduled_at: Time?,
            ?tenant: Knockapi::Models::inline_tenant_request?
          ) -> void

          def to_hash: -> Knockapi::Models::Schedules::BulkCreateSchedulesRequest::schedule
        end
      end
    end
  end
end
