module Knockapi
  module Models
    module Schedules
      type bulk_create_params =
        {
          schedules: ::Array[Knockapi::Models::Schedules::BulkCreateParams::Schedule]
        }
        & Knockapi::Internal::Type::request_parameters

      class BulkCreateParams < Knockapi::Internal::Type::BaseModel
        extend Knockapi::Internal::Type::RequestParameters::Converter
        include Knockapi::Internal::Type::RequestParameters

        attr_accessor schedules: ::Array[Knockapi::Models::Schedules::BulkCreateParams::Schedule]

        def initialize: (
          schedules: ::Array[Knockapi::Models::Schedules::BulkCreateParams::Schedule],
          ?request_options: Knockapi::request_opts
        ) -> void

        def to_hash: -> Knockapi::Models::Schedules::bulk_create_params

        type schedule =
          {
            workflow: String,
            actor: Knockapi::Models::recipient_request?,
            data: ::Hash[Symbol, top]?,
            ending_at: Time?,
            recipient: Knockapi::Models::recipient_request,
            repeats: ::Array[Knockapi::Models::ScheduleRepeatRule],
            scheduled_at: Time?,
            tenant: Knockapi::Models::Schedules::BulkCreateParams::Schedule::tenant?
          }

        class Schedule < Knockapi::Internal::Type::BaseModel
          attr_accessor workflow: String

          attr_accessor actor: Knockapi::Models::recipient_request?

          attr_accessor data: ::Hash[Symbol, top]?

          attr_accessor ending_at: Time?

          attr_reader recipient: Knockapi::Models::recipient_request?

          def recipient=: (
            Knockapi::Models::recipient_request
          ) -> Knockapi::Models::recipient_request

          attr_reader repeats: ::Array[Knockapi::Models::ScheduleRepeatRule]?

          def repeats=: (
            ::Array[Knockapi::Models::ScheduleRepeatRule]
          ) -> ::Array[Knockapi::Models::ScheduleRepeatRule]

          attr_accessor scheduled_at: Time?

          attr_accessor tenant: Knockapi::Models::Schedules::BulkCreateParams::Schedule::tenant?

          def initialize: (
            workflow: String,
            ?actor: Knockapi::Models::recipient_request?,
            ?data: ::Hash[Symbol, top]?,
            ?ending_at: Time?,
            ?recipient: Knockapi::Models::recipient_request,
            ?repeats: ::Array[Knockapi::Models::ScheduleRepeatRule],
            ?scheduled_at: Time?,
            ?tenant: Knockapi::Models::Schedules::BulkCreateParams::Schedule::tenant?
          ) -> void

          def to_hash: -> Knockapi::Models::Schedules::BulkCreateParams::schedule

          type tenant = String | Knockapi::Models::TenantRequest

          module Tenant
            extend Knockapi::Internal::Type::Union

            def self?.variants: -> [String, Knockapi::Models::TenantRequest]
          end
        end
      end
    end
  end
end
