module Knock
  class Error < StandardError
    attr_reader cause: StandardError?
  end

  class ConversionError < Knock::Error
  end

  class APIError < Knock::Error
    attr_reader url: URI::Generic

    attr_reader status: Integer?

    attr_reader body: top?

    def initialize: (
      url: URI::Generic,
      status: Integer?,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIConnectionError < Knock::APIError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APITimeoutError < Knock::APIConnectionError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIStatusError < Knock::APIError
    def self.for: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> instance

    def initialize: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class BadRequestError < Knock::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < Knock::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < Knock::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < Knock::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < Knock::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < Knock::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < Knock::APIStatusError
    HTTP_STATUS: 429
  end

  class InternalServerError < Knock::APIStatusError
    HTTP_STATUS: Range[Integer]
  end
end
