module Knock
  module Models
    module Providers
      type ms_team_list_channels_params =
        {
          ms_teams_tenant_object: String,
          team_id: String,
          query_options: Knock::Models::Providers::MsTeamListChannelsParams::QueryOptions
        }
        & Knock::request_parameters

      class MsTeamListChannelsParams < Knock::BaseModel
        extend Knock::RequestParameters::Converter
        include Knock::RequestParameters

        attr_accessor ms_teams_tenant_object: String

        attr_accessor team_id: String

        attr_reader query_options: Knock::Models::Providers::MsTeamListChannelsParams::QueryOptions?

        def query_options=: (
          Knock::Models::Providers::MsTeamListChannelsParams::QueryOptions
        ) -> Knock::Models::Providers::MsTeamListChannelsParams::QueryOptions

        def initialize:
          (
            ms_teams_tenant_object: String,
            team_id: String,
            query_options: Knock::Models::Providers::MsTeamListChannelsParams::QueryOptions,
            request_options: Knock::request_opts
          ) -> void
          | (
            ?Knock::Models::Providers::ms_team_list_channels_params
            | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Providers::ms_team_list_channels_params

        type query_options = { filter: String, select_: String }

        class QueryOptions < Knock::BaseModel
          attr_reader filter: String?

          def filter=: (String) -> String

          attr_reader select_: String?

          def select_=: (String) -> String

          def initialize:
            (filter: String, select_: String) -> void
            | (
              ?Knock::Models::Providers::MsTeamListChannelsParams::query_options
              | Knock::BaseModel data
            ) -> void

          def to_hash: -> Knock::Models::Providers::MsTeamListChannelsParams::query_options
        end
      end
    end
  end
end
