module Knockapi
  class EntriesCursor[Elem]
    include Knockapi::BasePage[Elem]

    attr_accessor entries: ::Array[Elem]?

    attr_accessor page_info: PageInfo

    def inspect: -> String

    type page_info = { after: String }
    class PageInfo < Knockapi::BaseModel
      attr_reader after: String?

      def after=: (String) -> String

      def initialize:
        (?after: String) -> void
        | (?page_info | Knockapi::BaseModel data) -> void

      def to_hash: -> page_info
    end
  end
end
