module Knockapi
  class Error < StandardError
    attr_accessor cause: StandardError?
  end

  class ConversionError < Knockapi::Error
  end

  class APIError < Knockapi::Error
    attr_accessor url: URI::Generic

    attr_accessor status: Integer?

    attr_accessor body: top?

    def initialize: (
      url: URI::Generic,
      status: Integer?,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIConnectionError < Knockapi::APIError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APITimeoutError < Knockapi::APIConnectionError
    def initialize: (
      url: URI::Generic,
      status: nil,
      body: nil,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class APIStatusError < Knockapi::APIError
    def self.for: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> instance

    def initialize: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      message: String?
    ) -> void
  end

  class BadRequestError < Knockapi::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < Knockapi::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < Knockapi::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < Knockapi::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < Knockapi::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < Knockapi::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < Knockapi::APIStatusError
    HTTP_STATUS: 429
  end

  class InternalServerError < Knockapi::APIStatusError
    HTTP_STATUS: Range[Integer]
  end
end
