module Knockapi
  class PooledNetRequester
    type request =
      {
        method: Symbol,
        url: URI::Generic,
        headers: ::Hash[String, String],
        body: top,
        deadline: Float
      }

    def self.connect: (URI::Generic url) -> top

    def self.calibrate_socket_timeout: (top conn, Float deadline) -> void

    def self.build_request: (
      Knockapi::PooledNetRequester::request request
    ) {
      (String arg0) -> void
    } -> top

    private def with_pool: (URI::Generic url) { (top arg0) -> void } -> void

    def execute: (
      Knockapi::PooledNetRequester::request request
    ) -> [top, Enumerable[String]]

    def initialize: (size: Integer) -> void
  end
end
