module Knockapi
  class SlackChannelsCursor[Elem]
    include Knockapi::Type::BasePage[Elem]

    attr_accessor next_cursor: String

    attr_accessor slack_channels: ::Array[Elem]?

    def inspect: -> String
  end
end
