module Knockapi
  class Unknown = Knockapi::Type::Unknown

  class BooleanModel = Knockapi::Type::BooleanModel

  module Enum = Knockapi::Type::Enum

  module Union = Knockapi::Type::Union

  class ArrayOf = Knockapi::Type::ArrayOf

  class HashOf = Knockapi::Type::HashOf

  class BaseModel = Knockapi::Type::BaseModel

  type request_parameters = Knockapi::Type::request_parameters

  module RequestParameters = Knockapi::Type::RequestParameters

  module Type
  end
end
