module Knockapi
  module Type
    module Converter
      type input = Knockapi::Type::Converter | Class

      type state =
        {
          strictness: bool | :strong,
          exactness: { yes: Integer, no: Integer, maybe: Integer },
          branched: Integer
        }

      def coerce: (top value, state: Knockapi::Type::Converter::state) -> top

      def dump: (top value) -> top

      def self.type_info: (
        {
          const: (nil | bool | Integer | Float | Symbol)?,
          enum: ^-> Knockapi::Type::Converter::input?,
          union: ^-> Knockapi::Type::Converter::input?
        }
        | ^-> Knockapi::Type::Converter::input
        | Knockapi::Type::Converter::input spec
      ) -> (^-> top)

      def self.coerce: (
        Knockapi::Type::Converter::input target,
        top value,
        ?state: Knockapi::Type::Converter::state
      ) -> top

      def self.dump: (Knockapi::Type::Converter::input target, top value) -> top
    end
  end
end
