module Knockapi
  module Type
    class Unknown
      extend Knockapi::Type::Converter

      def self.===: (top other) -> bool

      def self.==: (top other) -> bool

      def self.coerce: (
        top value,
        state: Knockapi::Type::Converter::state
      ) -> top

      def self.dump: (top value) -> top
    end
  end
end
