module Knockapi
  module Internal
    module Type
      class ArrayOf[Elem]
        include Knockapi::Internal::Type::Converter

        def self.[]: (
          ::Hash[Symbol, top]
          | ^-> Knockapi::Internal::Type::Converter::input
          | Knockapi::Internal::Type::Converter::input type_info,
          ?::Hash[Symbol, top] spec
        ) -> instance

        def ===: (top other) -> bool

        def ==: (top other) -> bool

        def coerce: (
          ::Array[top] | top value,
          state: Knockapi::Internal::Type::Converter::state
        ) -> (::Array[top] | top)

        def dump: (::Array[top] | top value) -> (::Array[top] | top)

        def item_type: -> Elem

        def nilable?: -> bool

        def initialize: (
          ::Hash[Symbol, top]
          | ^-> Knockapi::Internal::Type::Converter::input
          | Knockapi::Internal::Type::Converter::input type_info,
          ?::Hash[Symbol, top] spec
        ) -> void
      end
    end
  end
end
