module Knockapi
  module Internal
    module Type
      module Union
        include Knockapi::Internal::Type::Converter

        private def self.known_variants: -> ::Array[[Symbol?, (^-> Knockapi::Internal::Type::Converter::input)]]

        def self.derefed_variants: -> ::Array[[Symbol?, top]]

        def self.variants: -> ::Array[top]

        private def self.discriminator: (Symbol property) -> void

        private def self.variant: (
          Symbol
          | ::Hash[Symbol, top]
          | ^-> Knockapi::Internal::Type::Converter::input
          | Knockapi::Internal::Type::Converter::input key,
          ?::Hash[Symbol, top]
          | ^-> Knockapi::Internal::Type::Converter::input
          | Knockapi::Internal::Type::Converter::input spec
        ) -> void

        private def self.resolve_variant: (
          top value
        ) -> Knockapi::Internal::Type::Converter::input?

        def ===: (top other) -> bool

        def ==: (top other) -> bool

        def hash: -> Integer

        def coerce: (
          top value,
          state: Knockapi::Internal::Type::Converter::coerce_state
        ) -> top

        def dump: (
          top value,
          state: Knockapi::Internal::Type::Converter::dump_state
        ) -> top

        def inspect: (?depth: Integer) -> String
      end
    end
  end
end
