module Knockapi
  module Internal
    class ItemsCursor[Elem]
      include Knockapi::Internal::Type::BasePage[Elem]

      attr_accessor items: ::Array[Elem]?

      attr_accessor page_info: PageInfo

      def inspect: -> String

      type page_info = { after: String }
      class PageInfo < Knockapi::Internal::Type::BaseModel
        attr_reader after: String?

        def after=: (String) -> String

        def initialize: (?after: String) -> void

        def to_hash: -> { after: String }
      end
    end
  end
end
