module Knock
  module Models
    module Users
      type bulk_identify_params =
        { users: ::Array[Knock::Models::InlineIdentifyUserRequest] }
        & Knock::request_parameters

      class BulkIdentifyParams < Knock::BaseModel
        extend Knock::RequestParameters::Converter
        include Knock::RequestParameters

        attr_accessor users: ::Array[Knock::Models::InlineIdentifyUserRequest]

        def initialize:
          (
            users: ::Array[Knock::Models::InlineIdentifyUserRequest],
            request_options: Knock::request_opts
          ) -> void
          | (
            ?Knock::Models::Users::bulk_identify_params | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Users::bulk_identify_params
      end
    end
  end
end
