module Knock
  module Models
    module Users
      type bulk_delete_params =
        { user_ids: ::Array[String] } & Knock::request_parameters

      class BulkDeleteParams < Knock::BaseModel
        extend Knock::RequestParameters::Converter
        include Knock::RequestParameters

        attr_accessor user_ids: ::Array[String]

        def initialize:
          (
            user_ids: ::Array[String],
            request_options: Knock::request_opts
          ) -> void
          | (
            ?Knock::Models::Users::bulk_delete_params | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Users::bulk_delete_params
      end
    end
  end
end
