module Knock
  module Models
    module Users
      type feed_get_settings_response =
        { features: Knock::Models::Users::FeedGetSettingsResponse::Features }

      class FeedGetSettingsResponse < Knock::BaseModel
        attr_accessor features: Knock::Models::Users::FeedGetSettingsResponse::Features

        def initialize:
          (
            features: Knock::Models::Users::FeedGetSettingsResponse::Features
          ) -> void
          | (
            ?Knock::Models::Users::feed_get_settings_response
            | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Users::feed_get_settings_response

        type features = { branding_required: bool }

        class Features < Knock::BaseModel
          attr_accessor branding_required: bool

          def initialize:
            (branding_required: bool) -> void
            | (
              ?Knock::Models::Users::FeedGetSettingsResponse::features
              | Knock::BaseModel data
            ) -> void

          def to_hash: -> Knock::Models::Users::FeedGetSettingsResponse::features
        end
      end
    end
  end
end
