module Knockapi
  module Resources
    class Audiences
      def add_members: (
        String key,
        members: ::Array[Knockapi::AudienceAddMembersParams::Member],
        ?request_options: Knockapi::request_opts
      ) -> nil

      def list_members: (
        String key,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::AudienceListMembersResponse

      def remove_members: (
        String key,
        members: ::Array[Knockapi::AudienceRemoveMembersParams::Member],
        ?request_options: Knockapi::request_opts
      ) -> nil

      def initialize: (client: Knockapi::Client) -> void
    end
  end
end
