module Knockapi
  module Resources
    class Objects
      attr_reader bulk: Knockapi::Resources::Objects::Bulk

      def list: (
        String collection,
        ?after: String,
        ?before: String,
        ?include: ::Array[Knockapi::Models::ObjectListParams::include_],
        ?page_size: Integer,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Internal::EntriesCursor[Knockapi::Models::Object]

      def add_subscriptions: (
        String collection,
        String object_id_,
        recipients: ::Array[Knockapi::Models::recipient_request],
        ?properties: ::Hash[Symbol, top]?,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::object_add_subscriptions_response

      def delete_subscriptions: (
        String collection,
        String object_id_,
        recipients: ::Array[Knockapi::Models::recipient_reference],
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::object_delete_subscriptions_response

      def get_channel_data: (
        String collection,
        String object_id_,
        String channel_id,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::Recipients::RecipientsChannelData

      def list_preferences: (
        String collection,
        String object_id_,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::object_list_preferences_response

      def list_subscriptions: (
        String collection,
        String object_id_,
        ?after: String,
        ?before: String,
        ?include: ::Array[Knockapi::Models::ObjectListSubscriptionsParams::include_],
        ?mode: Knockapi::Models::ObjectListSubscriptionsParams::mode,
        ?objects: ::Array[Knockapi::Models::recipient_reference],
        ?page_size: Integer,
        ?recipients: ::Array[Knockapi::Models::recipient_reference],
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Internal::EntriesCursor[Knockapi::Models::Recipients::Subscription]

      def set_channel_data: (
        String collection,
        String object_id_,
        String channel_id,
        data: Knockapi::Models::Recipients::ChannelDataRequest::data,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::Recipients::RecipientsChannelData

      def unset_channel_data: (
        String collection,
        String object_id_,
        String channel_id,
        ?request_options: Knockapi::request_opts
      ) -> String

      def initialize: (client: Knockapi::Client) -> void
    end
  end
end
