module Knockapi
  module Resources
    class Schedules
      def create: (
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::schedule_create_response

      def update: (
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::schedule_update_response

      def list: (
        workflow: String,
        ?after: String,
        ?before: String,
        ?page_size: Integer,
        ?recipients: ::Array[Knockapi::Models::ScheduleListParams::recipient],
        ?tenant: String,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Internal::EntriesCursor[Knockapi::Models::Schedule]

      def delete: (
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::schedule_delete_response

      def initialize: (client: Knockapi::Client) -> void
    end
  end
end
