module Knockapi
  module Resources
    class Tenants
      attr_reader bulk: Knockapi::Resources::Tenants::Bulk

      def list: (
        ?after: String,
        ?before: String,
        ?name: String,
        ?page_size: Integer,
        ?tenant_id: String,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Internal::EntriesCursor[Knockapi::Models::Tenant]

      def delete: (
        String tenant_id,
        ?request_options: Knockapi::request_opts
      ) -> String

      def get: (
        String tenant_id,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::Tenant

      def set: (
        String tenant_id,
        ?channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        ?preferences: Knockapi::Models::Recipients::inline_preference_set_request?,
        ?settings: Knockapi::Models::TenantSetParams::Settings,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::Tenant

      def initialize: (client: Knockapi::Client) -> void
    end
  end
end
