module Knockapi
  module Resources
    class Tenants
      attr_reader bulk: Knockapi::Resources::Tenants::Bulk

      def list: (
        ?after: String,
        ?before: String,
        ?name: String,
        ?page_size: Integer,
        ?tenant_id: String,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Internal::EntriesCursor[Knockapi::Tenant]

      def delete: (String id, ?request_options: Knockapi::request_opts) -> nil

      def get: (
        String id,
        ?resolve_full_preference_settings: bool,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Tenant

      def set: (
        String id,
        ?resolve_full_preference_settings: bool,
        ?channel_data: Knockapi::Models::Recipients::inline_channel_data_request?,
        ?name: String?,
        ?settings: Knockapi::TenantSetParams::Settings,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Tenant

      def initialize: (client: Knockapi::Client) -> void
    end
  end
end
