module Knockapi
  module Resources
    class WorkflowRecipientRuns
      def list: (
        ?after: String,
        ?before: String,
        ?ending_at: Time,
        ?has_errors: bool,
        ?page_size: Integer,
        ?recipient: Knockapi::Models::recipient_reference,
        ?starting_at: Time,
        ?status: ::Array[Knockapi::Models::WorkflowRecipientRunListParams::status],
        ?tenant: String,
        ?workflow: String,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Internal::ItemsCursor[Knockapi::WorkflowRecipientRun]

      def get: (
        String id,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::WorkflowRecipientRunDetail

      def initialize: (client: Knockapi::Client) -> void
    end
  end
end
