module Knockapi
  module Resources
    class Workflows
      def cancel: (
        String key,
        cancellation_key: String,
        ?recipients: ::Array[String]?,
        ?request_options: Knockapi::request_opts
      ) -> String

      def trigger: (
        String key,
        recipients: ::Array[Knockapi::Models::recipient_request],
        ?actor: Knockapi::Models::recipient_request?,
        ?cancellation_key: String?,
        ?data: ::Hash[Symbol, top]?,
        ?tenant: Knockapi::Models::inline_tenant_request?,
        ?request_options: Knockapi::request_opts
      ) -> Knockapi::Models::WorkflowTriggerResponse

      def initialize: (client: Knockapi::Client) -> void
    end
  end
end
