module Knock
  module Resources
    class Users
      class Bulk
        def delete:
          (
            Knock::Models::Users::BulkDeleteParams | ::Hash[Symbol, top] params
          ) -> Knock::Models::BulkOperation
          | (
            user_ids: ::Array[String],
            request_options: Knock::request_opts
          ) -> Knock::Models::BulkOperation

        def identify:
          (
            Knock::Models::Users::BulkIdentifyParams
            | ::Hash[Symbol, top] params
          ) -> Knock::Models::BulkOperation
          | (
            users: ::Array[Knock::Models::InlineIdentifyUserRequest],
            request_options: Knock::request_opts
          ) -> Knock::Models::BulkOperation

        def set_preferences:
          (
            Knock::Models::Users::BulkSetPreferencesParams
            | ::Hash[Symbol, top] params
          ) -> Knock::Models::BulkOperation
          | (
            preferences: Knock::Models::PreferenceSetRequest,
            user_ids: ::Array[String],
            request_options: Knock::request_opts
          ) -> Knock::Models::BulkOperation

        def initialize: (client: Knock::Client) -> void
      end
    end
  end
end
