module Knock
  module Resources
    class Users
      class Feeds
        def get_settings:
          (
            String user_id,
            String channel_id,
            ?Knock::Models::Users::FeedGetSettingsParams
            | ::Hash[Symbol, top] params
          ) -> Knock::Models::Users::FeedGetSettingsResponse
          | (
            String user_id,
            String channel_id,
            request_options: Knock::request_opts
          ) -> Knock::Models::Users::FeedGetSettingsResponse

        def list_items:
          (
            String user_id,
            String channel_id,
            ?Knock::Models::Users::FeedListItemsParams
            | ::Hash[Symbol, top] params
          ) -> Knock::EntriesCursor[Knock::Models::Users::FeedListItemsResponse]
          | (
            String user_id,
            String channel_id,
            after: String,
            archived: Knock::Models::Users::FeedListItemsParams::archived,
            before: String,
            has_tenant: bool,
            page_size: Integer,
            source: String,
            status: Knock::Models::Users::FeedListItemsParams::status,
            tenant: String,
            trigger_data: String,
            workflow_categories: ::Array[String],
            request_options: Knock::request_opts
          ) -> Knock::EntriesCursor[Knock::Models::Users::FeedListItemsResponse]

        def initialize: (client: Knock::Client) -> void
      end
    end
  end
end
