module Knockapi
  module Models
    module Integrations
      type census_custom_destination_params =
        {
          id: String,
          jsonrpc: String,
          method_: String,
          params: ::Hash[Symbol, top]
        }
        & Knockapi::Internal::Type::request_parameters

      class CensusCustomDestinationParams < Knockapi::Internal::Type::BaseModel
        extend Knockapi::Internal::Type::RequestParameters::Converter
        include Knockapi::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor jsonrpc: String

        attr_accessor method_: String

        attr_reader params: ::Hash[Symbol, top]?

        def params=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        def initialize: (
          id: String,
          jsonrpc: String,
          method_: String,
          ?params: ::Hash[Symbol, top],
          ?request_options: Knockapi::request_opts
        ) -> void
      end
    end
  end
end
