module Knock
  module Models
    type identify_user_request =
      {
        channel_data: Knock::Models::inline_channel_data_request?,
        created_at: Time?,
        preferences: Knock::Models::inline_preference_set_request?
      }

    class IdentifyUserRequest < Knock::BaseModel
      attr_accessor channel_data: Knock::Models::inline_channel_data_request?

      attr_accessor created_at: Time?

      attr_accessor preferences: Knock::Models::inline_preference_set_request?

      def initialize:
        (
          channel_data: Knock::Models::inline_channel_data_request?,
          created_at: Time?,
          preferences: Knock::Models::inline_preference_set_request?
        ) -> void
        | (
          ?Knock::Models::identify_user_request | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::identify_user_request
    end
  end
end
