module Knock
  module Models
    type inline_object_request =
      {
        id: String,
        collection: String,
        channel_data: Knock::Models::inline_channel_data_request?,
        created_at: Time?,
        preferences: Knock::Models::inline_preference_set_request?
      }

    class InlineObjectRequest < Knock::BaseModel
      attr_accessor id: String

      attr_accessor collection: String

      attr_accessor channel_data: Knock::Models::inline_channel_data_request?

      attr_accessor created_at: Time?

      attr_accessor preferences: Knock::Models::inline_preference_set_request?

      def initialize:
        (
          id: String,
          collection: String,
          channel_data: Knock::Models::inline_channel_data_request?,
          created_at: Time?,
          preferences: Knock::Models::inline_preference_set_request?
        ) -> void
        | (
          ?Knock::Models::inline_object_request | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::inline_object_request
    end
  end
end
