module Knock
  module Models
    type message_list_activities_params =
      {
        after: String,
        before: String,
        page_size: Integer,
        trigger_data: String
      }
      & Knock::request_parameters

    class MessageListActivitiesParams < Knock::BaseModel
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader trigger_data: String?

      def trigger_data=: (String) -> String

      def initialize:
        (
          after: String,
          before: String,
          page_size: Integer,
          trigger_data: String,
          request_options: Knock::request_opts
        ) -> void
        | (
          ?Knock::Models::message_list_activities_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::message_list_activities_params
    end
  end
end
