module Knock
  module Models
    type message_mark_as_interacted_params =
      { metadata: ::Hash[Symbol, top] } & Knock::request_parameters

    class MessageMarkAsInteractedParams < Knock::BaseModel
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_reader metadata: ::Hash[Symbol, top]?

      def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize:
        (
          metadata: ::Hash[Symbol, top],
          request_options: Knock::request_opts
        ) -> void
        | (
          ?Knock::Models::message_mark_as_interacted_params
          | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::message_mark_as_interacted_params
    end
  end
end
