module Knock
  module Models
    type object_set_channel_data_params = {  } & Knock::request_parameters

    class ObjectSetChannelDataParams < Knock::Models::ChannelDataRequest
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      def initialize:
        (request_options: Knock::request_opts) -> void
        | (
          ?Knock::Models::object_set_channel_data_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::object_set_channel_data_params
    end
  end
end
