module Knock
  module Models
    type object_set_preferences_params = {  } & Knock::request_parameters

    class ObjectSetPreferencesParams < Knock::Models::PreferenceSetRequest
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      def initialize:
        (request_options: Knock::request_opts) -> void
        | (
          ?Knock::Models::object_set_preferences_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::object_set_preferences_params
    end
  end
end
