module Knock
  module Models
    type object_get_preferences_params =
      { collection: String, object_id_: String, tenant: String }
      & Knock::request_parameters

    class ObjectGetPreferencesParams < Knock::BaseModel
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_accessor collection: String

      attr_accessor object_id_: String

      attr_reader tenant: String?

      def tenant=: (String) -> String

      def initialize:
        (
          collection: String,
          object_id_: String,
          tenant: String,
          request_options: Knock::request_opts
        ) -> void
        | (
          ?Knock::Models::object_get_preferences_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::object_get_preferences_params
    end
  end
end
