module Knock
  module Models
    type one_signal_channel_data = { player_ids: ::Array[String] }

    class OneSignalChannelData < Knock::BaseModel
      attr_accessor player_ids: ::Array[String]

      def initialize:
        (player_ids: ::Array[String]) -> void
        | (
          ?Knock::Models::one_signal_channel_data | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::one_signal_channel_data
    end
  end
end
