module Knock
  module Models
    type preference_set_channel_type_setting =
      { conditions: ::Array[Knock::Models::Condition] }

    class PreferenceSetChannelTypeSetting < Knock::BaseModel
      attr_accessor conditions: ::Array[Knock::Models::Condition]

      def initialize:
        (conditions: ::Array[Knock::Models::Condition]) -> void
        | (
          ?Knock::Models::preference_set_channel_type_setting
          | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::preference_set_channel_type_setting
    end
  end
end
