module Knock
  module Models
    type preference_set_request =
      {
        categories: ::Hash[Symbol, Knock::Models::PreferenceSetRequest::category]?,
        channel_types: Knock::Models::PreferenceSetChannelTypes?,
        workflows: ::Hash[Symbol, Knock::Models::PreferenceSetRequest::workflow]?
      }

    class PreferenceSetRequest < Knock::BaseModel
      attr_accessor categories: ::Hash[Symbol, Knock::Models::PreferenceSetRequest::category]?

      attr_accessor channel_types: Knock::Models::PreferenceSetChannelTypes?

      attr_accessor workflows: ::Hash[Symbol, Knock::Models::PreferenceSetRequest::workflow]?

      def initialize:
        (
          categories: ::Hash[Symbol, Knock::Models::PreferenceSetRequest::category]?,
          channel_types: Knock::Models::PreferenceSetChannelTypes?,
          workflows: ::Hash[Symbol, Knock::Models::PreferenceSetRequest::workflow]?
        ) -> void
        | (
          ?Knock::Models::preference_set_request | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::preference_set_request

      type category =
        bool
        | Knock::Models::PreferenceSetRequest::Category::PreferenceSetWorkflowCategorySettingObject

      class Category < Knock::Union
        type preference_set_workflow_category_setting_object =
          {
            channel_types: Knock::Models::PreferenceSetChannelTypes?,
            conditions: ::Array[Knock::Models::Condition]?
          }

        class PreferenceSetWorkflowCategorySettingObject < Knock::BaseModel
          attr_accessor channel_types: Knock::Models::PreferenceSetChannelTypes?

          attr_accessor conditions: ::Array[Knock::Models::Condition]?

          def initialize:
            (
              channel_types: Knock::Models::PreferenceSetChannelTypes?,
              conditions: ::Array[Knock::Models::Condition]?
            ) -> void
            | (
              ?Knock::Models::PreferenceSetRequest::Category::preference_set_workflow_category_setting_object
              | Knock::BaseModel data
            ) -> void

          def to_hash: -> Knock::Models::PreferenceSetRequest::Category::preference_set_workflow_category_setting_object
        end

        private def self.variants: -> [[nil, bool], [nil, Knock::Models::PreferenceSetRequest::Category::PreferenceSetWorkflowCategorySettingObject]]
      end

      type workflow =
        bool
        | Knock::Models::PreferenceSetRequest::Workflow::PreferenceSetWorkflowCategorySettingObject

      class Workflow < Knock::Union
        type preference_set_workflow_category_setting_object =
          {
            channel_types: Knock::Models::PreferenceSetChannelTypes?,
            conditions: ::Array[Knock::Models::Condition]?
          }

        class PreferenceSetWorkflowCategorySettingObject < Knock::BaseModel
          attr_accessor channel_types: Knock::Models::PreferenceSetChannelTypes?

          attr_accessor conditions: ::Array[Knock::Models::Condition]?

          def initialize:
            (
              channel_types: Knock::Models::PreferenceSetChannelTypes?,
              conditions: ::Array[Knock::Models::Condition]?
            ) -> void
            | (
              ?Knock::Models::PreferenceSetRequest::Workflow::preference_set_workflow_category_setting_object
              | Knock::BaseModel data
            ) -> void

          def to_hash: -> Knock::Models::PreferenceSetRequest::Workflow::preference_set_workflow_category_setting_object
        end

        private def self.variants: -> [[nil, bool], [nil, Knock::Models::PreferenceSetRequest::Workflow::PreferenceSetWorkflowCategorySettingObject]]
      end
    end
  end
end
