module Knock
  module Models
    type schedule_create_params =
      {
        recipients: ::Array[Knock::Models::ScheduleCreateParams::recipient],
        repeats: ::Array[Knock::Models::ScheduleRepeatRule],
        workflow: String,
        data: ::Hash[Symbol, top]?,
        ending_at: Time?,
        scheduled_at: Time?,
        tenant: Knock::Models::inline_tenant_request?
      }
      & Knock::request_parameters

    class ScheduleCreateParams < Knock::BaseModel
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_accessor recipients: ::Array[Knock::Models::ScheduleCreateParams::recipient]

      attr_accessor repeats: ::Array[Knock::Models::ScheduleRepeatRule]

      attr_accessor workflow: String

      attr_accessor data: ::Hash[Symbol, top]?

      attr_accessor ending_at: Time?

      attr_accessor scheduled_at: Time?

      attr_accessor tenant: Knock::Models::inline_tenant_request?

      def initialize:
        (
          recipients: ::Array[Knock::Models::ScheduleCreateParams::recipient],
          repeats: ::Array[Knock::Models::ScheduleRepeatRule],
          workflow: String,
          data: ::Hash[Symbol, top]?,
          ending_at: Time?,
          scheduled_at: Time?,
          tenant: Knock::Models::inline_tenant_request?,
          request_options: Knock::request_opts
        ) -> void
        | (
          ?Knock::Models::schedule_create_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::schedule_create_params

      type recipient =
        String | Knock::Models::ScheduleCreateParams::Recipient::ObjectReference

      class Recipient < Knock::Union
        type object_reference = { id: String, collection: String }

        class ObjectReference < Knock::BaseModel
          attr_accessor id: String

          attr_accessor collection: String

          def initialize:
            (id: String, collection: String) -> void
            | (
              ?Knock::Models::ScheduleCreateParams::Recipient::object_reference
              | Knock::BaseModel data
            ) -> void

          def to_hash: -> Knock::Models::ScheduleCreateParams::Recipient::object_reference
        end

        private def self.variants: -> [[nil, String], [nil, Knock::Models::ScheduleCreateParams::Recipient::ObjectReference]]
      end
    end
  end
end
