module Knock
  module Models
    type user_merge_params =
      { from_user_id: String } & Knock::request_parameters

    class UserMergeParams < Knock::BaseModel
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_accessor from_user_id: String

      def initialize:
        (from_user_id: String, request_options: Knock::request_opts) -> void
        | (?Knock::Models::user_merge_params | Knock::BaseModel data) -> void

      def to_hash: -> Knock::Models::user_merge_params
    end
  end
end
