module Knock
  module Models
    type user_unset_channel_data_params =
      { user_id: String } & Knock::request_parameters

    class UserUnsetChannelDataParams < Knock::BaseModel
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_accessor user_id: String

      def initialize:
        (user_id: String, request_options: Knock::request_opts) -> void
        | (
          ?Knock::Models::user_unset_channel_data_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::user_unset_channel_data_params
    end
  end
end
