module Knock
  module Models
    type user_set_preferences_params =
      { user_id: String } & Knock::request_parameters

    class UserSetPreferencesParams < Knock::Models::PreferenceSetRequest
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_accessor user_id: String

      def initialize:
        (user_id: String, request_options: Knock::request_opts) -> void
        | (
          ?Knock::Models::user_set_preferences_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::user_set_preferences_params
    end
  end
end
