module Knock
  module Models
    type workflow_trigger_response = { workflow_run_id: String }

    class WorkflowTriggerResponse < Knock::BaseModel
      attr_accessor workflow_run_id: String

      def initialize:
        (workflow_run_id: String) -> void
        | (
          ?Knock::Models::workflow_trigger_response | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::workflow_trigger_response
    end
  end
end
