module Knock
  module Models
    type workflow_trigger_params =
      {
        actor: Knock::Models::recipient_request?,
        cancellation_key: String?,
        data: ::Hash[Symbol, top]?,
        recipients: ::Array[Knock::Models::recipient_request],
        tenant: Knock::Models::inline_tenant_request?
      }
      & Knock::request_parameters

    class WorkflowTriggerParams < Knock::BaseModel
      extend Knock::RequestParameters::Converter
      include Knock::RequestParameters

      attr_accessor actor: Knock::Models::recipient_request?

      attr_accessor cancellation_key: String?

      attr_accessor data: ::Hash[Symbol, top]?

      attr_reader recipients: ::Array[Knock::Models::recipient_request]?

      def recipients=: (
        ::Array[Knock::Models::recipient_request]
      ) -> ::Array[Knock::Models::recipient_request]

      attr_accessor tenant: Knock::Models::inline_tenant_request?

      def initialize:
        (
          actor: Knock::Models::recipient_request?,
          cancellation_key: String?,
          data: ::Hash[Symbol, top]?,
          recipients: ::Array[Knock::Models::recipient_request],
          tenant: Knock::Models::inline_tenant_request?,
          request_options: Knock::request_opts
        ) -> void
        | (
          ?Knock::Models::workflow_trigger_params | Knock::BaseModel data
        ) -> void

      def to_hash: -> Knock::Models::workflow_trigger_params
    end
  end
end
