module Knock
  module Models
    module Messages
      type batch_get_content_params =
        { message_ids: ::Array[String] } & Knock::request_parameters

      class BatchGetContentParams < Knock::BaseModel
        extend Knock::RequestParameters::Converter
        include Knock::RequestParameters

        attr_accessor message_ids: ::Array[String]

        def initialize:
          (
            message_ids: ::Array[String],
            request_options: Knock::request_opts
          ) -> void
          | (
            ?Knock::Models::Messages::batch_get_content_params
            | Knock::BaseModel data
          ) -> void

        def to_hash: -> Knock::Models::Messages::batch_get_content_params
      end
    end
  end
end
