module Knockapi
  module Models
    module Recipients
      type aws_sns_push_channel_data_devices_only =
        {
          devices: ::Array[Knockapi::Recipients::AwsSnsPushChannelDataDevicesOnly::Device]
        }

      class AwsSnsPushChannelDataDevicesOnly < Knockapi::Internal::Type::BaseModel
        attr_accessor devices: ::Array[Knockapi::Recipients::AwsSnsPushChannelDataDevicesOnly::Device]

        def initialize: (
          devices: ::Array[Knockapi::Recipients::AwsSnsPushChannelDataDevicesOnly::Device]
        ) -> void

        def to_hash: -> {
          devices: ::Array[Knockapi::Recipients::AwsSnsPushChannelDataDevicesOnly::Device]
        }

        type device = { target_arn: String, locale: String?, timezone: String? }

        class Device < Knockapi::Internal::Type::BaseModel
          attr_accessor target_arn: String

          attr_accessor locale: String?

          attr_accessor timezone: String?

          def initialize: (
            target_arn: String,
            ?locale: String?,
            ?timezone: String?
          ) -> void

          def to_hash: -> {
            target_arn: String,
            locale: String?,
            timezone: String?
          }
        end
      end
    end
  end
end
