module Knockapi
  module Models
    module Recipients
      type channel_data_request =
        { data: Knockapi::Models::Recipients::ChannelDataRequest::data }

      class ChannelDataRequest < Knockapi::Internal::Type::BaseModel
        attr_accessor data: Knockapi::Models::Recipients::ChannelDataRequest::data

        def initialize: (
          data: Knockapi::Models::Recipients::ChannelDataRequest::data
        ) -> void

        def to_hash: -> Knockapi::Models::Recipients::channel_data_request

        type data =
          Knockapi::Models::Recipients::OneSignalChannelData
          | Knockapi::Models::Recipients::SlackChannelData
          | Knockapi::Models::Recipients::MsTeamsChannelData
          | Knockapi::Models::Recipients::DiscordChannelData
          | Knockapi::Models::Recipients::PushChannelData

        module Data
          extend Knockapi::Internal::Type::Union

          def self?.variants: -> [Knockapi::Models::Recipients::OneSignalChannelData, Knockapi::Models::Recipients::SlackChannelData, Knockapi::Models::Recipients::MsTeamsChannelData, Knockapi::Models::Recipients::DiscordChannelData, Knockapi::Models::Recipients::PushChannelData]
        end
      end
    end
  end
end
