module Knockapi
  module Models
    module Recipients
      type recipients_channel_data =
        {
          channel_id: String,
          data: Knockapi::Models::Recipients::RecipientsChannelData::data,
          provider: Knockapi::Models::Recipients::RecipientsChannelData::provider
        }

      class RecipientsChannelData < Knockapi::Internal::Type::BaseModel
        attr_accessor channel_id: String

        attr_accessor data: Knockapi::Models::Recipients::RecipientsChannelData::data

        attr_reader provider: Knockapi::Models::Recipients::RecipientsChannelData::provider?

        def provider=: (
          Knockapi::Models::Recipients::RecipientsChannelData::provider
        ) -> Knockapi::Models::Recipients::RecipientsChannelData::provider

        def initialize: (
          channel_id: String,
          data: Knockapi::Models::Recipients::RecipientsChannelData::data,
          ?provider: Knockapi::Models::Recipients::RecipientsChannelData::provider
        ) -> void

        def to_hash: -> Knockapi::Models::Recipients::recipients_channel_data

        type data =
          Knockapi::Models::Recipients::PushChannelData
          | Knockapi::Models::Recipients::SlackChannelData
          | Knockapi::Models::Recipients::MsTeamsChannelData
          | Knockapi::Models::Recipients::DiscordChannelData
          | Knockapi::Models::Recipients::OneSignalChannelData

        module Data
          extend Knockapi::Internal::Type::Union

          def self?.variants: -> [Knockapi::Models::Recipients::PushChannelData, Knockapi::Models::Recipients::SlackChannelData, Knockapi::Models::Recipients::MsTeamsChannelData, Knockapi::Models::Recipients::DiscordChannelData, Knockapi::Models::Recipients::OneSignalChannelData]
        end

        type provider =
          :push_fcm
          | :push_apns
          | :push_expo
          | :push_one_signal
          | :chat_slack
          | :chat_ms_teams
          | :chat_discord
          | :http_knock_webhook

        module Provider
          extend Knockapi::Internal::Type::Enum

          PUSH_FCM: :push_fcm
          PUSH_APNS: :push_apns
          PUSH_EXPO: :push_expo
          PUSH_ONE_SIGNAL: :push_one_signal
          CHAT_SLACK: :chat_slack
          CHAT_MS_TEAMS: :chat_ms_teams
          CHAT_DISCORD: :chat_discord
          HTTP_KNOCK_WEBHOOK: :http_knock_webhook

          def self?.values: -> ::Array[Knockapi::Models::Recipients::RecipientsChannelData::provider]
        end
      end
    end
  end
end
