module Knockapi
  module Models
    module Recipients
      type discord_channel_data =
        {
          connections: ::Array[Knockapi::Models::Recipients::DiscordChannelData::connection],
          type: Knockapi::Models::Recipients::DiscordChannelData::type_,
          _typename: Knockapi::Models::Recipients::DiscordChannelData::typename
        }

      class DiscordChannelData < Knockapi::Internal::Type::BaseModel
        attr_accessor connections: ::Array[Knockapi::Models::Recipients::DiscordChannelData::connection]

        attr_accessor type: Knockapi::Models::Recipients::DiscordChannelData::type_

        attr_reader _typename: Knockapi::Models::Recipients::DiscordChannelData::typename?

        def _typename=: (
          Knockapi::Models::Recipients::DiscordChannelData::typename
        ) -> Knockapi::Models::Recipients::DiscordChannelData::typename

        def initialize: (
          connections: ::Array[Knockapi::Models::Recipients::DiscordChannelData::connection],
          type: Knockapi::Models::Recipients::DiscordChannelData::type_,
          ?_typename: Knockapi::Models::Recipients::DiscordChannelData::typename
        ) -> void

        def to_hash: -> Knockapi::Models::Recipients::discord_channel_data

        type connection =
          Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordChannelConnection
          | Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordIncomingWebhookConnection

        module Connection
          extend Knockapi::Internal::Type::Union

          type discord_channel_connection = { channel_id: String }

          class DiscordChannelConnection < Knockapi::Internal::Type::BaseModel
            attr_accessor channel_id: String

            def initialize: (channel_id: String) -> void

            def to_hash: -> Knockapi::Models::Recipients::DiscordChannelData::Connection::discord_channel_connection
          end

          type discord_incoming_webhook_connection =
            {
              incoming_webhook: Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordIncomingWebhookConnection::IncomingWebhook
            }

          class DiscordIncomingWebhookConnection < Knockapi::Internal::Type::BaseModel
            attr_accessor incoming_webhook: Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordIncomingWebhookConnection::IncomingWebhook

            def initialize: (
              incoming_webhook: Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordIncomingWebhookConnection::IncomingWebhook
            ) -> void

            def to_hash: -> Knockapi::Models::Recipients::DiscordChannelData::Connection::discord_incoming_webhook_connection

            type incoming_webhook = { url: String }

            class IncomingWebhook < Knockapi::Internal::Type::BaseModel
              attr_accessor url: String

              def initialize: (url: String) -> void

              def to_hash: -> Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordIncomingWebhookConnection::incoming_webhook
            end
          end

          def self?.variants: -> [Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordChannelConnection, Knockapi::Models::Recipients::DiscordChannelData::Connection::DiscordIncomingWebhookConnection]
        end

        type type_ = :chat_discord

        module Type
          extend Knockapi::Internal::Type::Enum

          CHAT_DISCORD: :chat_discord

          def self?.values: -> ::Array[Knockapi::Models::Recipients::DiscordChannelData::type_]
        end

        type typename = :DiscordChannelData

        module Typename
          extend Knockapi::Internal::Type::Enum

          DISCORD_CHANNEL_DATA: :DiscordChannelData

          def self?.values: -> ::Array[Knockapi::Models::Recipients::DiscordChannelData::typename]
        end
      end
    end
  end
end
