module Knockapi
  module Models
    module Recipients
      type inline_preference_set_request =
        ::Array[Knockapi::Models::Recipients::inline_preference_set_request]

      InlinePreferenceSetRequest: inline_preference_set_request
    end
  end
end
