module Knockapi
  module Models
    module Recipients
      type inline_preference_set_request_item =
        {
          id: String,
          categories: ::Hash[Symbol, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::category]?,
          channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
          workflows: ::Hash[Symbol, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::workflow]?
        }

      class InlinePreferenceSetRequestItem < Knockapi::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor categories: ::Hash[Symbol, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::category]?

        attr_accessor channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?

        attr_accessor workflows: ::Hash[Symbol, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::workflow]?

        def initialize: (
          id: String,
          ?categories: ::Hash[Symbol, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::category]?,
          ?channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
          ?workflows: ::Hash[Symbol, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::workflow]?
        ) -> void

        def to_hash: -> Knockapi::Models::Recipients::inline_preference_set_request_item

        type category =
          bool
          | Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::Category::PreferenceSetWorkflowCategorySettingObject

        module Category
          extend Knockapi::Internal::Type::Union

          type preference_set_workflow_category_setting_object =
            {
              channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              conditions: ::Array[Knockapi::Models::Condition]?
            }

          class PreferenceSetWorkflowCategorySettingObject < Knockapi::Internal::Type::BaseModel
            attr_accessor channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?

            attr_accessor conditions: ::Array[Knockapi::Models::Condition]?

            def initialize: (
              ?channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              ?conditions: ::Array[Knockapi::Models::Condition]?
            ) -> void

            def to_hash: -> Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::Category::preference_set_workflow_category_setting_object
          end

          def self?.variants: -> [bool, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::Category::PreferenceSetWorkflowCategorySettingObject]
        end

        type workflow =
          bool
          | Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::Workflow::PreferenceSetWorkflowCategorySettingObject

        module Workflow
          extend Knockapi::Internal::Type::Union

          type preference_set_workflow_category_setting_object =
            {
              channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              conditions: ::Array[Knockapi::Models::Condition]?
            }

          class PreferenceSetWorkflowCategorySettingObject < Knockapi::Internal::Type::BaseModel
            attr_accessor channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?

            attr_accessor conditions: ::Array[Knockapi::Models::Condition]?

            def initialize: (
              ?channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              ?conditions: ::Array[Knockapi::Models::Condition]?
            ) -> void

            def to_hash: -> Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::Workflow::preference_set_workflow_category_setting_object
          end

          def self?.variants: -> [bool, Knockapi::Models::Recipients::InlinePreferenceSetRequestItem::Workflow::PreferenceSetWorkflowCategorySettingObject]
        end
      end

      type inline_preference_set_request =
        ::Array[Knockapi::Models::Recipients::InlinePreferenceSetRequestItem]

      InlinePreferenceSetRequest: inline_preference_set_request
    end
  end
end
