module Knockapi
  module Models
    module Recipients
      type inline_preference_set_request =
        ::Hash[Symbol, Knockapi::Models::Recipients::PreferenceSetRequest]

      InlinePreferenceSetRequest: Knockapi::Internal::Type::Converter
    end
  end
end
