module Knockapi
  module Models
    module Recipients
      type one_signal_channel_data = { player_ids: ::Array[String] }

      class OneSignalChannelData < Knockapi::Internal::Type::BaseModel
        attr_accessor player_ids: ::Array[String]

        def initialize: (player_ids: ::Array[String]) -> void

        def to_hash: -> { player_ids: ::Array[String] }
      end
    end
  end
end
