module Knockapi
  module Models
    module Recipients
      type preference_set =
        {
          id: String,
          _typename: String,
          categories: ::Hash[Symbol, Knockapi::Models::Recipients::PreferenceSet::category]?,
          channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
          workflows: ::Hash[Symbol, Knockapi::Models::Recipients::PreferenceSet::workflow]?
        }

      class PreferenceSet < Knockapi::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor _typename: String

        attr_accessor categories: ::Hash[Symbol, Knockapi::Models::Recipients::PreferenceSet::category]?

        attr_accessor channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?

        attr_accessor workflows: ::Hash[Symbol, Knockapi::Models::Recipients::PreferenceSet::workflow]?

        def initialize: (
          id: String,
          _typename: String,
          ?categories: ::Hash[Symbol, Knockapi::Models::Recipients::PreferenceSet::category]?,
          ?channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
          ?workflows: ::Hash[Symbol, Knockapi::Models::Recipients::PreferenceSet::workflow]?
        ) -> void

        def to_hash: -> Knockapi::Models::Recipients::preference_set

        type category =
          bool
          | Knockapi::Models::Recipients::PreferenceSet::Category::UnionMember1

        module Category
          extend Knockapi::Internal::Type::Union

          type union_member1 =
            {
              channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              conditions: ::Array[Knockapi::Models::Condition]
            }

          class UnionMember1 < Knockapi::Internal::Type::BaseModel
            attr_accessor channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?

            attr_reader conditions: ::Array[Knockapi::Models::Condition]?

            def conditions=: (
              ::Array[Knockapi::Models::Condition]
            ) -> ::Array[Knockapi::Models::Condition]

            def initialize: (
              ?channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              ?conditions: ::Array[Knockapi::Models::Condition]
            ) -> void

            def to_hash: -> Knockapi::Models::Recipients::PreferenceSet::Category::union_member1
          end

          def self?.variants: -> [bool, Knockapi::Models::Recipients::PreferenceSet::Category::UnionMember1]
        end

        type workflow =
          bool
          | Knockapi::Models::Recipients::PreferenceSet::Workflow::UnionMember1

        module Workflow
          extend Knockapi::Internal::Type::Union

          type union_member1 =
            {
              channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              conditions: ::Array[Knockapi::Models::Condition]
            }

          class UnionMember1 < Knockapi::Internal::Type::BaseModel
            attr_accessor channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?

            attr_reader conditions: ::Array[Knockapi::Models::Condition]?

            def conditions=: (
              ::Array[Knockapi::Models::Condition]
            ) -> ::Array[Knockapi::Models::Condition]

            def initialize: (
              ?channel_types: Knockapi::Models::Recipients::PreferenceSetChannelTypes?,
              ?conditions: ::Array[Knockapi::Models::Condition]
            ) -> void

            def to_hash: -> Knockapi::Models::Recipients::PreferenceSet::Workflow::union_member1
          end

          def self?.variants: -> [bool, Knockapi::Models::Recipients::PreferenceSet::Workflow::UnionMember1]
        end
      end
    end
  end
end
