module Knockapi
  module Models
    module Recipients
      type slack_channel_data =
        {
          connections: ::Array[Knockapi::Models::Recipients::SlackChannelData::connection],
          type: Knockapi::Models::Recipients::SlackChannelData::type_,
          token: Knockapi::Models::Recipients::SlackChannelData::Token?,
          _typename: Knockapi::Models::Recipients::SlackChannelData::typename
        }

      class SlackChannelData < Knockapi::Internal::Type::BaseModel
        attr_accessor connections: ::Array[Knockapi::Models::Recipients::SlackChannelData::connection]

        attr_accessor type: Knockapi::Models::Recipients::SlackChannelData::type_

        attr_accessor token: Knockapi::Models::Recipients::SlackChannelData::Token?

        attr_reader _typename: Knockapi::Models::Recipients::SlackChannelData::typename?

        def _typename=: (
          Knockapi::Models::Recipients::SlackChannelData::typename
        ) -> Knockapi::Models::Recipients::SlackChannelData::typename

        def initialize: (
          connections: ::Array[Knockapi::Models::Recipients::SlackChannelData::connection],
          type: Knockapi::Models::Recipients::SlackChannelData::type_,
          ?token: Knockapi::Models::Recipients::SlackChannelData::Token?,
          ?_typename: Knockapi::Models::Recipients::SlackChannelData::typename
        ) -> void

        def to_hash: -> Knockapi::Models::Recipients::slack_channel_data

        type connection =
          Knockapi::Models::Recipients::SlackChannelData::Connection::SlackTokenConnection
          | Knockapi::Models::Recipients::SlackChannelData::Connection::SlackIncomingWebhookConnection

        module Connection
          extend Knockapi::Internal::Type::Union

          type slack_token_connection =
            { access_token: String?, channel_id: String?, user_id: String? }

          class SlackTokenConnection < Knockapi::Internal::Type::BaseModel
            attr_accessor access_token: String?

            attr_accessor channel_id: String?

            attr_accessor user_id: String?

            def initialize: (
              ?access_token: String?,
              ?channel_id: String?,
              ?user_id: String?
            ) -> void

            def to_hash: -> Knockapi::Models::Recipients::SlackChannelData::Connection::slack_token_connection
          end

          type slack_incoming_webhook_connection = { url: String }

          class SlackIncomingWebhookConnection < Knockapi::Internal::Type::BaseModel
            attr_accessor url: String

            def initialize: (url: String) -> void

            def to_hash: -> Knockapi::Models::Recipients::SlackChannelData::Connection::slack_incoming_webhook_connection
          end

          def self?.variants: -> [Knockapi::Models::Recipients::SlackChannelData::Connection::SlackTokenConnection, Knockapi::Models::Recipients::SlackChannelData::Connection::SlackIncomingWebhookConnection]
        end

        type type_ = :chat_slack

        module Type
          extend Knockapi::Internal::Type::Enum

          CHAT_SLACK: :chat_slack

          def self?.values: -> ::Array[Knockapi::Models::Recipients::SlackChannelData::type_]
        end

        type token = { access_token: String? }

        class Token < Knockapi::Internal::Type::BaseModel
          attr_accessor access_token: String?

          def initialize: (access_token: String?) -> void

          def to_hash: -> Knockapi::Models::Recipients::SlackChannelData::token
        end

        type typename = :SlackChannelData

        module Typename
          extend Knockapi::Internal::Type::Enum

          SLACK_CHANNEL_DATA: :SlackChannelData

          def self?.values: -> ::Array[Knockapi::Models::Recipients::SlackChannelData::typename]
        end
      end
    end
  end
end
