module Knockapi
  module Resources
    class Providers
      class MsTeams
        def check_auth: (
          String channel_id,
          ms_teams_tenant_object: String,
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::Models::Providers::MsTeamCheckAuthResponse

        def list_channels: (
          String channel_id,
          ms_teams_tenant_object: String,
          team_id: String,
          ?query_options: Knockapi::Models::Providers::MsTeamListChannelsParams::QueryOptions,
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::Models::Providers::MsTeamListChannelsResponse

        def list_teams: (
          String channel_id,
          ms_teams_tenant_object: String,
          ?query_options: Knockapi::Models::Providers::MsTeamListTeamsParams::QueryOptions,
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::Models::Providers::MsTeamListTeamsResponse

        def revoke_access: (
          String channel_id,
          ms_teams_tenant_object: String,
          ?request_options: Knockapi::request_opts
        ) -> Knockapi::Models::Providers::MsTeamRevokeAccessResponse

        def initialize: (client: Knockapi::Client) -> void
      end
    end
  end
end
